# NETSICE output 

After the NETISCE computations are complete, the output files will be located in the `results` folder. Please note that we have included in this folder the most relevant output files that you may want to use for further analysis. However, you can explore all outputs by checking within each step of the pipeline's `work` folder that is generated during a NETISCE run. 

The contents of each file are briefly described below. For more details and to see example outputs, please see the [Toy Network Examples](#toy).

#### exp_internalmarkers.txt {-#section-id}
This file contains the resultant steady state values for the internal marker nodes for the provided experimental samples (those specified in samples.txt) from Signal Flow Analysis.

#### experimental_internalmarkers.pdf {-#section-id}
This pdf is a figure of the steady state values for the internal marker nodes for the provided experimental samples. This can be used to verify the validity of the internal marker nodes.

#### elbow.png  {-#section-id}
A graph of the elbow metric for determining the optimal k for k-means.

#### silhouette.png {-#section-id}
A graph of the silhouette metric for determining the optimal k for k-means.

#### fvs.txt  {-#section-id}
This file contains the node names for the FVS used as control nodes for the NETISCE run.

#### crit1perts.txt  {-#section-id}
This file contains a list of IDs for the control node perturbations that passed criterion 1.

#### pert1_internal_markers.txt  {-#section-id}
This file contains a table of the internal marker node steady state  values from control node perturbations whose associated attractors passed the first filtering criterion. 

#### successful_controlnode_perturbations.txt  {-#section-id}
This file contains a table of the control node perturbations that pass both the 1st and 2nd filtering criteria. it also contains the number of upregulation,downregulations, and total number of nodes perturbed for each perturbation set. 
