#!/bin/bash
#SBATCH -D /labs/Vera-Licona/pipeline_validation_2021/kinoshita_FINAL/kinoshita_automation/work/6a/8d864741c4048be83eeeddaeef5766
#SBATCH -J nf-classification
#SBATCH -o /labs/Vera-Licona/pipeline_validation_2021/kinoshita_FINAL/kinoshita_automation/work/6a/8d864741c4048be83eeeddaeef5766/.command.log
#SBATCH --no-requeue
#SBATCH --qos=general --mem=4G
# NEXTFLOW TASK: classification
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}


nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

on_exit() {
    exit_status=${nxf_main_ret:=$?}
    printf $exit_status > /labs/Vera-Licona/pipeline_validation_2021/kinoshita_FINAL/kinoshita_automation/work/6a/8d864741c4048be83eeeddaeef5766/.exitcode
    set +u
    [[ "$tee1" ]] && kill $tee1 2>/dev/null
    [[ "$tee2" ]] && kill $tee2 2>/dev/null
    [[ "$ctmp" ]] && rm -rf $ctmp || true
    exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

nxf_launch() {
    /bin/bash -ue /labs/Vera-Licona/pipeline_validation_2021/kinoshita_FINAL/kinoshita_automation/work/6a/8d864741c4048be83eeeddaeef5766/.command.sh
}

nxf_stage() {
    true
    # stage input files
    rm -f kmeans.txt
    rm -f pert1
    rm -f pert2
    rm -f pert3
    rm -f samples.txt
    rm -f attrs_exp.txt
    rm -f attrs_insilico
    ln -s /labs/Vera-Licona/pipeline_validation_2021/kinoshita_FINAL/kinoshita_automation/work/ec/0df85de71f4f1602087a880da2f634/kmeans.txt kmeans.txt
    ln -s /labs/Vera-Licona/pipeline_validation_2021/kinoshita_FINAL/kinoshita_automation/work/3c/6792979fa351d6cc26caebb6c103b2/pert_logss_EpiSC_1_.txt pert1
    ln -s /labs/Vera-Licona/pipeline_validation_2021/kinoshita_FINAL/kinoshita_automation/work/3c/6792979fa351d6cc26caebb6c103b2/pert_logss_EpiSC_2_.txt pert2
    ln -s /labs/Vera-Licona/pipeline_validation_2021/kinoshita_FINAL/kinoshita_automation/work/3c/6792979fa351d6cc26caebb6c103b2/pert_logss_EpiSC_3_.txt pert3
    ln -s /labs/Vera-Licona/pipeline_validation_2021/kinoshita_FINAL/kinoshita_automation/input_data/samples.txt samples.txt
    ln -s /labs/Vera-Licona/pipeline_validation_2021/kinoshita_FINAL/kinoshita_automation/work/8b/960016b35f76c3a8c213676cfd5652/attrs_exp.txt attrs_exp.txt
    ln -s /labs/Vera-Licona/pipeline_validation_2021/kinoshita_FINAL/kinoshita_automation/work/c6/ecc3518a9ffc61609f6e85fd9757bb/attrs_insilico.txt attrs_insilico
}

nxf_unstage() {
    true
    [[ ${nxf_main_ret:=0} != 0 ]] && return
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /labs/Vera-Licona/pipeline_validation_2021/kinoshita_FINAL/kinoshita_automation/work/6a/8d864741c4048be83eeeddaeef5766/.command.begin
    set +u
    set -u
    export PATH="/labs/Vera-Licona/pipeline_validation_2021/kinoshita_FINAL/kinoshita_automation/bin:$PATH"
    [[ $NXF_SCRATCH ]] && echo "nxf-scratch-dir $HOSTNAME:$NXF_SCRATCH" && cd $NXF_SCRATCH
    nxf_stage

    set +e
    local ctmp=$(set +u; nxf_mktemp /dev/shm 2>/dev/null || nxf_mktemp $TMPDIR)
    local cout=$ctmp/.command.out; mkfifo $cout
    local cerr=$ctmp/.command.err; mkfifo $cerr
    tee .command.out < $cout &
    tee1=$!
    tee .command.err < $cerr >&2 &
    tee2=$!
    ( nxf_launch ) >$cout 2>$cerr &
    pid=$!
    wait $pid || nxf_main_ret=$?
    wait $tee1 $tee2
    nxf_unstage
}

$NXF_ENTRY
