% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{book}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={NETISCE Manual and Tutorials},
  pdfauthor={Lauren Marazzi},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs}
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{booktabs}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage[]{natbib}
\bibliographystyle{plainnat}

\title{NETISCE Manual and Tutorials}
\author{Lauren Marazzi}
\date{2021-12-24}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{1}
\tableofcontents
}
\hypertarget{about}{%
\chapter{About}\label{about}}

Welcome to the NETISCE manual and tutorials.

Cell-fate reprogramming is a powerful type of cellular reprogramming which aims to drive a system from a selected initial state towards a desired phenotype. However, methods for identifying reprogramming targets remain limited in biological systems that lack large sets of experimental data or dynamical characterization. We present here NETISCE, a novel computational method for identifying cell-fate reprogramming targets and their perturbations in static networks through the application of control theory and dynamical systems frameworks to a network-based analysis. Our method only requires a static network and the gene expression data for the initial state of the system. We validate NETISCE in studies of cell-fate reprogramming from developmental, stem cell, and cancer biology. Our results show that NETISCE can predict previously identified cell-fate reprogramming target perturbations in these systems, and identify potentially novel combinations of targets. This work extends cell-fate reprogramming studies beyond fully parameterized models and can be used by experimental and computational biologists to guide their cell-fate reprogramming studies.

For more information, please see the accompanying paper: \textbf{link here}

This manual contains instructions for installing the NETISCE pipeline tool and accessing the Galaxy Project GUI web-based tool. We provide a simple toy example walkthrough tutorial. Lastly, we include instructions for reproducing NETISCE cell reprogramming results in developmental, stem cell, and cancer biology.

\hypertarget{installation-and-usage}{%
\chapter{Installation and Usage}\label{installation-and-usage}}

\hypertarget{download-netisce}{%
\section{Download NETISCE}\label{download-netisce}}

NETISCE pipelines can be downloaded from our github repository: \url{https://github.com/veraliconaresearchgroup/netisce}

We recommend that you run NETISCE on a high-performance cluster (hpc), as you may generate files that are quite large, or run computations that may take a long time. However, we provide two Nextflow pipelines, one designed for hpcs \href{https://github.com/VeraLiconaResearchGroup/Netisce/tree/main/NETICSE_hpc}{(NETISCE\_hpc)}, and another for running NETISCE on a local machine \href{https://github.com/VeraLiconaResearchGroup/Netisce/tree/main/NETICSE_local}{(NETISCE\_local)}.

\hypertarget{install-nextflow}{%
\section{Install Nextflow}\label{install-nextflow}}

Nextflow is required to run the NETISCE pipeline. Please follow the instructions from \url{https://www.nextflow.io/} (see `Getting Started' steps 1 \& 2) to install Nextflow in the appropriate NETSICE folder (\_local or \_hpc).

\hypertarget{docker-image}{%
\section{Docker Image}\label{docker-image}}

\emph{docker image provided here TBD}

\hypertarget{prerequisuites}{%
\section{Prerequisuites}\label{prerequisuites}}

If you are not using the Docker image, the following packages will need to be installed:

\begin{itemize}
\tightlist
\item
  \href{https://scipy.org/install/}{scipy}
\item
  \href{https://pandas.pydata.org/getting_started.html}{pandas}
\item
  \href{https://scikit-learn.org/stable/install.html}{sklearn}
\item
  \href{https://www.scikit-yb.org/en/latest/quickstart.html}{yellowbrick}
\end{itemize}

\hypertarget{params}{%
\section{Parameters and Configuration}\label{params}}

Whether on your local machine or hpc, to run NETISCE you must specify the files and parameters within the \texttt{.nf} file

\begin{itemize}
\tightlist
\item
  \textbf{params.expressions}: csv file containing normalized expression data for network nodes in different samples
\item
  \textbf{params.network}: network file (sif format)
\item
  \textbf{params.samples}: text file specifying the phenotype for each sample in params.expressions file (tab delimited)
\item
  \textbf{params.internal\_control}: text file containing a list of nodes to be used as internal marker nodes
\item
  \textbf{params.alpha}: alpha parameter for signal flow analysis (default =0.9)
\item
  \textbf{params.undesired}: string of the undesired phenotype (as labeled in the params.samples file)
\item
  \textbf{params.desired}: string of the desired phenotype (as labeled in the params.samples file)
\item
  \textbf{params.filter}: filtering parameter for criterion 2 (``strict'' or ``relaxed'')
\item
  \textbf{params.kmeans\_min\_val}: minimum k-means value for clustering (default=2)
\item
  \textbf{params.kmeans\_max\_val}: maximum k-means value for clustering (default=10)
\item
  \textbf{params.num\_nodes}: number of nodes in network for which normalized expression data exists (within the params.expressions file)
\item
  \textbf{params.num\_states}: number of randomly generated initial states (default=100000, or 3\^{}n where n is the number of network nodes and 3\^{}n is less than 100000)
\end{itemize}

Please see the \href{https://github.com/VeraLiconaResearchGroup/Netisce/tree/main/NETISCE_local/input_data}{\texttt{input\_data}} folder for examples of files to match the formatting.

\hypertarget{netisce_mutations.nf}{%
\subsection{NETISCE\_mutations.nf}\label{netisce_mutations.nf}}

If you are interested in including mutational information, please use the \href{https://github.com/VeraLiconaResearchGroup/Netisce/blob/main/NETISCE_local/NETISCE_mutations.nf}{\texttt{NETISCE\_mutations.nf}} pipeline. You must additionally specify \texttt{params.mutations}: a csv file containing mutational configuration for network nodes (0 for loss of function, 1 for gain of function). Please see example in \href{https://github.com/VeraLiconaResearchGroup/Netisce/tree/main/NETISCE_local/input_data}{\texttt{input\_data}} for formatting.

\hypertarget{nextflow.config}{%
\subsection{nextflow.config}\label{nextflow.config}}

If you are running nextflow on an hpc, please specify your executor, and clusterOptions within the nextflow.config file. Please see \url{https://www.nextflow.io/docs/latest/config.html} for more information regarding your executor.

\hypertarget{running-netisce}{%
\section{Running NETISCE}\label{running-netisce}}

Once you have specified the parameters, run NETSICE using the following command:

\begin{verbatim}
./nextflow run NETISCE.nf -resume ##or NETISCE_mutations.nf if including mutational data
\end{verbatim}

We recommend using the -resume flag in the case that you change a file or parameter within your pipeline. This way, nextflow caches results that remain unchanged, preventing pipeline steps from being re-run.

\hypertarget{netsice-output}{%
\chapter{NETSICE output}\label{netsice-output}}

After the NETISCE computations are complete, the output files will be located in the \texttt{results} folder. Please note that we have included in this folder the most relevant output files that you may want to use for further analysis. However, you can explore all outputs by checking within each step of the pipeline's \texttt{work} folder that is generated during a NETISCE run.

The contents of each file are briefly described below. For more details and to see example outputs, please see the \protect\hyperlink{toy}{Toy Network Examples}.

\hypertarget{section-id}{%
\subsubsection*{exp\_internalmarkers.txt}\label{section-id}}
\addcontentsline{toc}{subsubsection}{exp\_internalmarkers.txt}

This file contains the resultant steady state values for the internal marker nodes for the provided experimental samples (those specified in samples.txt) from Signal Flow Analysis.

\hypertarget{section-id}{%
\subsubsection*{experimental\_internalmarkers.pdf}\label{section-id}}
\addcontentsline{toc}{subsubsection}{experimental\_internalmarkers.pdf}

This pdf is a figure of the steady state values for the internal marker nodes for the provided experimental samples. This can be used to verify the validity of the internal marker nodes.

\hypertarget{section-id}{%
\subsubsection*{elbow.png}\label{section-id}}
\addcontentsline{toc}{subsubsection}{elbow.png}

A graph of the elbow metric for determining the optimal k for k-means.

\hypertarget{section-id}{%
\subsubsection*{silhouette.png}\label{section-id}}
\addcontentsline{toc}{subsubsection}{silhouette.png}

A graph of the silhouette metric for determining the optimal k for k-means.

\hypertarget{section-id}{%
\subsubsection*{fvs.txt}\label{section-id}}
\addcontentsline{toc}{subsubsection}{fvs.txt}

This file contains the node names for the FVS used as control nodes for the NETISCE run.

\hypertarget{section-id}{%
\subsubsection*{crit1perts.txt}\label{section-id}}
\addcontentsline{toc}{subsubsection}{crit1perts.txt}

This file contains a list of IDs for the control node perturbations that passed criterion 1.

\hypertarget{section-id}{%
\subsubsection*{pert1\_internal\_markers.txt}\label{section-id}}
\addcontentsline{toc}{subsubsection}{pert1\_internal\_markers.txt}

This file contains a table of the internal marker node steady state values from control node perturbations whose associated attractors passed the first filtering criterion.

\hypertarget{section-id}{%
\subsubsection*{successful\_controlnode\_perturbations.txt}\label{section-id}}
\addcontentsline{toc}{subsubsection}{successful\_controlnode\_perturbations.txt}

This file contains a table of the control node perturbations that pass both the 1st and 2nd filtering criteria. it also contains the number of upregulation,downregulations, and total number of nodes perturbed for each perturbation set.

\hypertarget{toy}{%
\chapter{Toy Network Examples}\label{toy}}

Here, we will walk through a brief tutorial of a NETISCE run. The files necessary to complete the tutorial are within the \texttt{input\ data} folder of both \href{https://github.com/VeraLiconaResearchGroup/Netisce/tree/main/NETICSE_local}{\texttt{NETISCE\_local}} and \href{https://github.com/VeraLiconaResearchGroup/Netisce/tree/main/NETICSE_hpc}{\texttt{NETISCE\_hpc}}.
The results from these Toy examples can be found in the \href{https://github.com/VeraLiconaResearchGroup/Netisce/tree/main/toy_example_results}{toy\_example\_results} folder of the main github repository.

\hypertarget{overview}{%
\section{Overview}\label{overview}}

We will use a simple toy network of 6 nodes and 9 edges.

\begin{figure}

{\centering \includegraphics[width=0.5\linewidth]{images/toy_network} 

}

\caption{Simple Toy Network}\label{fig:unnamed-chunk-3}
\end{figure}

\hypertarget{data}{%
\section{Data}\label{data}}

You can find the relevant data files in the \texttt{input\_data} folder.

In this example, we have 2 samples, A and B, with three replicates each (A\_1,A\_2,A\_3, etc).
The normalized expression data is housed in \texttt{expressions.csv}, and contains normalized expression values for 4 of the network nodes (in this case, node C was not found to be expressed in the samples).

\begin{tabular}{l|r|r|r|r|r|r}
\hline
X & A\_1 & A\_2 & A\_3 & B\_1 & B\_2 & B\_3\\
\hline
A & 2 & 1 & 2 & 6 & 7 & 6\\
\hline
B & 6 & 7 & 6 & 2 & 1 & 1\\
\hline
D & -1 & -1 & -2 & 6 & 7 & 6\\
\hline
E & 2 & 1 & 2 & 6 & 7 & 6\\
\hline
\end{tabular}

The \texttt{samples.txt} file specifies that A is associated to a treatment sensitive phenotype, while B is associated to a resistance phenotype.

\begin{tabular}{l|l}
\hline
name & phenotype\\
\hline
A\_1 & sensitive\\
\hline
A\_2 & sensitive\\
\hline
A\_3 & sensitive\\
\hline
B\_1 & resistant\\
\hline
B\_2 & resistant\\
\hline
B\_3 & resistant\\
\hline
\end{tabular}

Note that you can use any term to describe the phenotypes. Just be sure to be consistent with the \texttt{param.desried} and \texttt{param.undesired} variables within the Nextflow \texttt{.nf} file.

Lastly, we need to include a list of internal marker nodes. This list is in \texttt{internal\_marker.txt}. For our small network, the internal-marker node is \texttt{C}.

\begin{tabular}{l}
\hline
C\\


\hline
\end{tabular}

\hypertarget{netisce-run-configuration}{%
\section{NETISCE run configuration}\label{netisce-run-configuration}}

With all your input data files loaded, next we configure the nextflow run in either \texttt{NETISCE\_local} or \texttt{NETSICE\_hpc} (\textbf{Note: while we do recommend you run NETISCE on a hpc, this example is small enough to run locally}).

Open up \texttt{NETISCE.nf}. Here, you need to specify the parameters for the Nextflow run on lines 3-19. Please refer to \protect\hyperlink{params}{section 2.5} for parameter definitions.

For this example, your parameters should look like:

\begin{verbatim}
params.expressions = "$baseDir/input_data/expressions.csv"
params.network = "$baseDir/input_data/network.sif"
params.samples = "$baseDir/input_data/samples.txt"
params.internal_control="$baseDir/input_data/internal_marker.txt"
params.alpha = 0.9
params.undesired = 'resistant'
params.desired = 'sensitive'
params.filter ="strict"


params.kmeans_min_val = 2
params.kmeans_max_val = 10


params.num_nodes = 4 // that have expression data
params.num_states = 100000
\end{verbatim}

\textbf{Some Notes: } make sure to include \texttt{\$baseDir} before pointing to the folder containing your input data. Also, be sure that \texttt{params.num\_nodes} is the number of nodes where there exists normalized expression data within \texttt{expression.csv}.

\hypertarget{run-netisce}{%
\section{Run NETISCE}\label{run-netisce}}

In your terminal/command prompt, navigate to the appropriate NETISCE folder (\texttt{\_hpc} or \texttt{local}). To start your run, enter \texttt{./nextflow\ run\ NETISCE.nf\ -resume}.
While NETISCE is running, your terminal should look like this, where you can see the progress on each step of the pipeline:

\begin{figure}

{\centering \includegraphics[width=0.5\linewidth]{images/running_shot} 

}

\caption{Terminal when running NETISCE}\label{fig:unnamed-chunk-7}
\end{figure}

The first column contains the location (folder and subfolder) that is running that step of NETISCE within the \texttt{work} folder.

Once the run has successfully completed, the process will end and the following will be displayed:

\begin{figure}

{\centering \includegraphics[width=0.5\linewidth]{images/completed} 

}

\caption{Terminal when running NETISCE}\label{fig:unnamed-chunk-8}
\end{figure}

\hypertarget{netsice-results}{%
\section{NETSICE Results}\label{netsice-results}}

Let's take a look at the results of our NETISCE run, where the goal was to shift the system from the undesired state B, and towards the desired state A. These results can be found in the toy\_example\_1 subfolder of the \href{https://github.com/VeraLiconaResearchGroup/Netisce/tree/main/toy_example_results}{toy\_example\_results} folder of the main github repository.

\hypertarget{section-id}{%
\subsubsection*{exp\_internalmarkers.txt}\label{section-id}}
\addcontentsline{toc}{subsubsection}{exp\_internalmarkers.txt}

Our internal marker node was node C. In this file we see the steady state values of the node in the A and B sample replicates (the output values from SFA).

\begin{tabular}{l|r}
\hline
name & C\\
\hline
A\_1 & 0.4278056\\
\hline
A\_2 & 0.4802943\\
\hline
A\_3 & 0.4361991\\
\hline
B\_1 & 0.1590962\\
\hline
B\_2 & 0.0982107\\
\hline
B\_3 & 0.0935476\\
\hline
\end{tabular}

\hypertarget{section-id}{%
\subsubsection*{experimental\_internalmarkers.pdf}\label{section-id}}
\addcontentsline{toc}{subsubsection}{experimental\_internalmarkers.pdf}

The above numbers may be a little challenging to read! So, we have included a plot of the values in the\texttt{experimental\_internalmarkers.pdf}:

\begin{figure}

{\centering \includegraphics[width=0.5\linewidth]{images/expmarkers} 

}

\caption{experimental marker node steady state values}\label{fig:unnamed-chunk-10}
\end{figure}

On this histogram, we see bars for each of the samples and their replicates. The A (sensitive) samples are marked by a blue vertical line at their steady state value, while the B (resistant) samples are marked by a red vertical line at their steady state value. Here, we see that the values of node C are well separated between the two phenotypes (all of the A values are greater than all of the B values). We will assume that this also aligns with the biological knowledge of the system.

In this example, since there are only 4 network nodes that have normalized expression values, NETISCE generates the maximum number of random initial states, \(3^4\), or 81.

After estimating attractors for the experimental and randomly generated initial states, the resultant attractors were clustered using k-means clustering. The elbow and silhouette metrics are used to determine the optimal number k.

\hypertarget{section-id}{%
\subsubsection*{elbow.png}\label{section-id}}
\addcontentsline{toc}{subsubsection}{elbow.png}

\begin{figure}

{\centering \includegraphics[width=0.5\linewidth]{results/elbow} 

}

\caption{elbow metric for optimal k}\label{fig:unnamed-chunk-11}
\end{figure}

The elbow metric found the optimal number of k clusters to be k=3.

\hypertarget{section-id}{%
\subsubsection*{silhouette.png}\label{section-id}}
\addcontentsline{toc}{subsubsection}{silhouette.png}

\begin{figure}

{\centering \includegraphics[width=0.5\linewidth]{results/silhouette} 

}

\caption{silhouette metric for optimal k}\label{fig:unnamed-chunk-12}
\end{figure}

The silhouette metric found the optimal number of k clusters to be k=2.

Since the optimal ks identified by the silhouette metric and the elbow metric do not match, NETISCE chooses the smaller k, as long as the phenotypes remain separate (NETISCE checks to make sure this is true).

\hypertarget{section-id}{%
\subsubsection*{kmeans.txt}\label{section-id}}
\addcontentsline{toc}{subsubsection}{kmeans.txt}

The \texttt{kmeans.txt} file contains the clustering results for each attractor generated from the experimental data and the randomly generated initial states. The first column contains the sample name, and the second column contains the ID of which cluster it is assigned to. Since k=2 in this case, one cluster is named
``0'' and the other cluster is named ``1''

\begin{tabular}{l|r}
\hline
name & clusters\\
\hline
A\_1 & 0\\
\hline
A\_2 & 0\\
\hline
A\_3 & 0\\
\hline
B\_1 & 1\\
\hline
B\_2 & 1\\
\hline
B\_3 & 1\\
\hline
\end{tabular}

And we see in the \texttt{kmeans.txt} file, that the A samples are clustered in cluster 0, while the B samples are grouped in cluster 1.

\hypertarget{section-id}{%
\subsubsection*{fvs.txt}\label{section-id}}
\addcontentsline{toc}{subsubsection}{fvs.txt}

This file contains the node names that were identified by the FVS finding algorithm.

\begin{tabular}{l}
\hline
name\\
\hline
D\\
\hline
B\\
\hline
\end{tabular}

The FVS finding algorithm identified nodes B and D to be the minimal FVS control nodes in the toy network. Since the FVS control node set contained 2 nodes, 9 combinations of perturbations were performed on the control node sets.

\hypertarget{section-id}{%
\subsubsection*{crit1perts.txt}\label{section-id}}
\addcontentsline{toc}{subsubsection}{crit1perts.txt}

This file contains a list of IDs for the perturbations to FVS control nodes that passed criterion 1.

\begin{tabular}{l}
\hline
V1\\
\hline
pert\_0\\
\hline
pert\_1\\
\hline
pert\_2\\
\hline
pert\_4\\
\hline
pert\_5\\
\hline
pert\_6\\
\hline
pert\_7\\
\hline
pert\_8\\
\hline
\end{tabular}

8 out of the 9 pertrubations passed the machine learning filtering criterion.

\hypertarget{section-id}{%
\subsubsection*{pert1\_internal\_markers.txt}\label{section-id}}
\addcontentsline{toc}{subsubsection}{pert1\_internal\_markers.txt}

This file contains a table of the internal marker node state values from control node perturbations whose associated attractors passed the first filtering criterion.

\begin{tabular}{l|r}
\hline
name & C\\
\hline
pert\_0 & -2.7000000\\
\hline
pert\_1 & 1.0209997\\
\hline
pert\_2 & 6.3000000\\
\hline
pert\_4 & -0.0427445\\
\hline
pert\_5 & 6.3000000\\
\hline
pert\_6 & -2.7000000\\
\hline
pert\_7 & -2.8528056\\
\hline
pert\_8 & 6.3000000\\
\hline
\end{tabular}

\hypertarget{section-id}{%
\subsubsection*{successful\_controlnode\_perturbations.txt}\label{section-id}}
\addcontentsline{toc}{subsubsection}{successful\_controlnode\_perturbations.txt}

This file contains a table of the perturbations on FVS control nodes that passed both the 1st and 2nd filtering criteria. it also contains the number of upregulation,downregulations, and total number of nodes perturbed for each perturbation set.

\begin{tabular}{l|l|l|r|r|r}
\hline
  & D & B & up & down & total\\
\hline
pert\_1 & down & nochange & 0 & 1 & 1\\
\hline
pert\_5 & nochange & up & 1 & 0 & 1\\
\hline
pert\_2 & down & up & 1 & 1 & 2\\
\hline
pert\_8 & up & up & 2 & 0 & 2\\
\hline
\end{tabular}

Here, we see that four perturbations that passed both filtering criteria.

Let's take a quick look at the steady state values for these perturbations, and the attractors generated from the experimental data:

\begin{tabular}{l|l|r}
\hline
  & name & C\\
\hline
1 & A\_1 & 0.4278056\\
\hline
2 & A\_2 & 0.4802943\\
\hline
3 & A\_3 & 0.4361991\\
\hline
4 & B\_1 & 0.1590962\\
\hline
5 & B\_2 & 0.0982107\\
\hline
6 & B\_3 & 0.0935476\\
\hline
21 & pert\_1 & 1.0209997\\
\hline
31 & pert\_2 & 6.3000000\\
\hline
51 & pert\_5 & 6.3000000\\
\hline
8 & pert\_8 & 6.3000000\\
\hline
\end{tabular}

Indeed, we see that the steady-state expression values of node C in the attractors generated by peturbations to the FVS control nodes are all are greater than the steady-state expression values of node C in the attractors generated from the sensitive A sample. A successful reprogramming from resistant (B) to sensitive (A) cells has occurred!

\hypertarget{toy-example-with-mutations}{%
\section{Toy Example with mutations}\label{toy-example-with-mutations}}

Let's say that in our system, gene A exhibits a loss of function mutation in the sensitive phenotype (A samples). If we want to include this in our simulations, we will use the \texttt{NETISCE\_mutations.nf} pipeline.

First, we must add to our \texttt{input\_data} folder a \texttt{.csv} file containing the mutational profile. Let's call this file \texttt{mutations.csv}:

\begin{tabular}{l|r}
\hline
X & A\\
\hline
A\_1 & 0\\
\hline
A\_2 & 0\\
\hline
A\_3 & 0\\
\hline
B\_1 & NA\\
\hline
B\_2 & NA\\
\hline
B\_3 & NA\\
\hline
\end{tabular}

The loss of function mutation is encoded with 0 (gain-of-function mutations can be encoded with ``1'').

Next, we make sure that the parameters in \texttt{NETISCE\_mutations.nf} on lines 3-19 are set correctly for the conditions

For this example, your parameters should look like:

\begin{verbatim}
params.expressions = "$baseDir/input_data/expressions.csv"
params.network = "$baseDir/input_data/network.sif"
params.samples = "$baseDir/input_data/samples.txt"
params.internal_control="$baseDir/input_data/internal_marker.txt"
params.mutations="$baseDir/input_data/mutations.csv"
params.alpha = 0.9
params.undesired = 'resistant'
params.desired = 'sensitive'
params.filter ="strict"


params.kmeans_min_val = 2
params.kmeans_max_val = 10


params.num_nodes = 4 // that have expression data
params.num_states = 1000
\end{verbatim}

Note, the additional parameter \texttt{params.mutations} that points to the \texttt{mutations.csv.}

As above, to run Netisce, enter \texttt{./nextflow\ run\ NETISCE.nf\ -resume}.

\hypertarget{section-id}{%
\subsubsection*{Results}\label{section-id}}
\addcontentsline{toc}{subsubsection}{Results}

By including mutational information, the results of NETISCE have changed.These results can be found in the toy\_example\_2 subfolder of the \href{https://github.com/VeraLiconaResearchGroup/Netisce/tree/main/toy_example_results}{toy\_example\_results} folder of the main github repository.
Now, our \texttt{successful\_controlnode\_perturbations.txt} file contains pert\_0 instead of pert\_8

\begin{tabular}{l|l|l|r|r|r}
\hline
  & B & D & up & down & total\\
\hline
pert\_1 & down & nochange & 0 & 1 & 1\\
\hline
pert\_5 & nochange & up & 1 & 0 & 1\\
\hline
pert\_0 & down & down & 0 & 2 & 2\\
\hline
pert\_2 & down & up & 1 & 1 & 2\\
\hline
\end{tabular}

Let's take a look at the steady-state expression values of node C in the attractors generated from the successful perturbations and the experimental initial states when mutational information is included.

\begin{tabular}{l|r}
\hline
name & C\\
\hline
A\_1 & -0.6621166\\
\hline
B\_1 & 0.1590962\\
\hline
pert\_0 & -2.7000000\\
\hline
pert\_1 & -2.7000000\\
\hline
pert\_2 & -2.7000000\\
\hline
pert\_5 & -2.8528056\\
\hline
\end{tabular}

Though the values are different in this system with mutations, we still see that the steady-state expression values of node C in the attractors generated by peturbations to the FVS control nodes are all are greater than the steady-state expression values of node C in the attractors generated from the sensitive A sample. A successful reprogramming from resistant (B) to sensitive (A) cells has occurred!

\hypertarget{cell-fate-specification-in-ascidian-embryo}{%
\chapter{Cell Fate Specification in Ascidian Embryo}\label{cell-fate-specification-in-ascidian-embryo}}

This section contains instructions to reproduce the results of simulating FVS control node perturbations in a model of ascidian embryo cell specification. You can read the original report here: link

The input data, nextflow pipeline, and results of this simulation can be found in the \href{https://github.com/VeraLiconaResearchGroup/Netisce/tree/main/ascidian_embryo}{ascidian embryo folder} in the github repository

These simulations were run on a high performance cluster that uses a SLURM executor. Although we recommend that you run NETISCE on an hpc, this simulation is small enough that it can be run on a local machine. If you choose to run it locally, then remove the \texttt{nextflow.config} file from the directory.

\hypertarget{input-data}{%
\section{Input Data}\label{input-data}}

The goal of this simulation was to reproduce the results of experimental perturbations to the FVS nodes of the cell fate specification GRN for ascidian embryos using Signal Flow Analysis. Therefore, we use a modified version of the NETISCE pipeline to simulate these specific perturbations.
We are only interested in performing the 7 perturbations to the 6 FVS control nodes that were experimentally verified to induce cell tissue fates.

\texttt{expression.csv} contains the initial activities for the unperturbed state and the 7 FVS control node perturbations. Here, all simulations have Gata.a and Zic-r.a=1, as the activation of these two genes is required for normal embryonic development.

\texttt{perturbations.csv} contains the specified perturbations for each FVS node in the appropriate perturbation simulation. 0 denotes downregulation, wherease 1 encodes upregulation. If no value is set, then there is no fixed perturbation to the FVS node, as in the unperturbed case.

\texttt{internal-marker-nodes.txt} contains the 7 internal marker nodes used to verify if the specified cell reprogramming had been successfully simulated.

\hypertarget{run-the-simulation}{%
\section{Run the simulation}\label{run-the-simulation}}

To run the simulation, simply execute the \texttt{ascidian-embryo.nf} file using the following command: \texttt{./nextflow\ run\ ascidian-embryo.nf\ -resume}

\hypertarget{results}{%
\section{Results}\label{results}}

The nextflow pipeline generates 1 result file \texttt{exp\_internalmarkers.txt}, which contains the steady state values of the internal-marker nodes for the unperturbed attractor, and the attractors generated from the perturbations on FVS control nodes.

\begin{table}
\centering\begingroup\fontsize{8}{10}\selectfont

\begin{tabular}{l|r|r|r|r|r|r|r}
\hline
name & Alp & Bco & Celf3.a & Epi1 & Fli.Erg.a & Myl & Noto1\\
\hline
unperturbed & -0.0000341 & 0.0018729 & 0.0018729 & 0.0217995 & 0.0013966 & 0.0008975 & 0.0004029\\
\hline
Adentz (Endoderm perturbation) & 0.1179951 & -0.4252100 & -0.4252100 & 0.2707276 & -0.1836794 & -0.1396049 & 0.1169769\\
\hline
adentZ (brain+pan-neural perturbation) & -0.3845691 & 0.4252100 & 0.4252100 & 0.2707276 & -0.2370737 & -0.0041647 & 0.1123776\\
\hline
adeNtz (pan-neural perturbation) & -0.5243074 & -0.4252100 & -0.4252100 & 0.2707276 & -0.3002010 & -0.1063952 & 0.2408746\\
\hline
adEntZ (mesenchyme perturbation) & -0.2630083 & 0.4252100 & 0.4252100 & -0.1563935 & 0.2841288 & -0.0871440 & -0.0052551\\
\hline
adentz (epidermis perturbation) & -0.5243074 & -0.4252100 & -0.4252100 & 0.2707276 & -0.3002010 & -0.1237829 & 0.2349825\\
\hline
adenTz (muscle perturbation) & -0.5243074 & -0.4252100 & -0.4252100 & 0.2707276 & -0.3002010 & 0.0837375 & 0.2589035\\
\hline
aDentz (notochord perturbation) & -0.3792942 & -0.4252100 & -0.4252100 & 0.1988199 & -0.3966199 & -0.1218621 & 0.0943055\\
\hline
\end{tabular}
\endgroup{}
\end{table}

A perturbation is considered successful if the internal-marker node in the attractor generated from the perturbed FVS control nodes has a larger steady-state value than that in the unperturbed attractor. We determine this by subtracting the steady-state values of the unperturbed simulation from the steady-state values of the perturbations of FVS control nodes.

\begin{table}
\centering\begingroup\fontsize{9}{11}\selectfont

\begin{tabular}{l|l|l|l|l|l|l|l}
\hline
  & Alp & Bco & Celf3.a & Epi1 & Fli.Erg.a & Myl & Noto1\\
\hline
Adentz (Endoderm perturbation) & <span style="     border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: yellow !important;" >0.118</span> & -0.427 & -0.427 & 0.249 & -0.185 & -0.141 & 0.117\\
\hline
adentZ (brain+pan-neural perturbation) & -0.385 & <span style="     border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: yellow !important;" >0.423</span> & <span style="     border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: yellow !important;" >0.423</span> & 0.249 & -0.238 & -0.005 & 0.112\\
\hline
adeNtz (pan-neural perturbation) & -0.524 & -0.427 & -0.427 & 0.249 & -0.302 & -0.107 & 0.24\\
\hline
adEntZ (mesenchyme perturbation) & -0.263 & 0.423 & 0.423 & -0.178 & <span style="     border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: yellow !important;" >0.283</span> & -0.088 & -0.006\\
\hline
adentz (epidermis perturbation) & -0.524 & -0.427 & -0.427 & <span style="     border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: yellow !important;" >0.249</span> & -0.302 & -0.125 & 0.235\\
\hline
adenTz (muscle perturbation) & -0.524 & -0.427 & -0.427 & 0.249 & -0.302 & <span style="     border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: yellow !important;" >0.083</span> & 0.259\\
\hline
aDentz (notochord perturbation) & -0.379 & -0.427 & -0.427 & 0.177 & -0.398 & -0.123 & <span style="     border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: yellow !important;" >0.094</span>\\
\hline
\end{tabular}
\endgroup{}
\end{table}

Here we see that for 6 out of the 7 perturbations to FVS controlnodes, we were able to upregulate the desired tissue marker when compared to the unperturbed state.

\hypertarget{visualizing-results}{%
\section{Visualizing Results}\label{visualizing-results}}

We can use radar plots to visualize the results of the SFA simulations of perturbations to the FVS control nodes. This can help us identify which perturbations successfully induced the appropriate tissue fate. In this context.

The following code for generating radar plots was adapted from \href{https://www.google.com/search?q=create+_beautiful_+radar+chart\&oq=create+beautiful+rada\&aqs=chrome.1.69i57j0i10i22i30.11973j0j1\&sourceid=chrome\&ie=UTF-8}{datanovia.com}.

\textbf{Note: } you may need to adjust the formatting of \texttt{exp\_internalmarkers.txt} so that the strings within quotations are placed into one column.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{create_beautiful_radarchart <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(data, }\DataTypeTok{color =} \StringTok{"#00AFBB"}\NormalTok{, }
                                        \DataTypeTok{vlabels =} \KeywordTok{colnames}\NormalTok{(data), }\DataTypeTok{vlcex =} \DecValTok{1}\NormalTok{,}
                                        \DataTypeTok{caxislabels =} \OtherTok{NULL}\NormalTok{, }\DataTypeTok{title =}\KeywordTok{row.names}\NormalTok{(data)[}\DecValTok{4}\NormalTok{], ...)\{}
  \KeywordTok{radarchart}\NormalTok{(}
\NormalTok{    data, }\DataTypeTok{axistype =} \DecValTok{1}\NormalTok{,}
    \CommentTok{# Customize the polygon}
    \DataTypeTok{pcol =}\NormalTok{ color, }\DataTypeTok{pfcol =}\NormalTok{ scales}\OperatorTok{::}\KeywordTok{alpha}\NormalTok{(color, }\FloatTok{0.5}\NormalTok{), }\DataTypeTok{plwd =} \DecValTok{2}\NormalTok{, }\DataTypeTok{plty =} \DecValTok{1}\NormalTok{,}
    \CommentTok{# Customize the grid}
    \DataTypeTok{cglcol =} \StringTok{"grey"}\NormalTok{, }\DataTypeTok{cglty =} \DecValTok{1}\NormalTok{, }\DataTypeTok{cglwd =} \FloatTok{0.8}\NormalTok{,}
    \CommentTok{# Customize the axis}
    \DataTypeTok{axislabcol =} \StringTok{"grey"}\NormalTok{, }
    \CommentTok{# Variable labels}
    \DataTypeTok{vlcex =}\NormalTok{ vlcex, }\DataTypeTok{vlabels =}\NormalTok{ vlabels,}
    \DataTypeTok{title =}\NormalTok{ title,}
    \DataTypeTok{centerzero =}\NormalTok{ F,}
    \DataTypeTok{caxislabels =}\NormalTok{ caxislabels}
    
\NormalTok{  )}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(fmsb)}
\NormalTok{d1<-}\KeywordTok{read.delim}\NormalTok{(}\StringTok{"ascidian_embryo/results/exp_internalmarkers.txt"}\NormalTok{,}\DataTypeTok{sep=}\StringTok{"}\CharTok{\textbackslash{}t}\StringTok{"}\NormalTok{,}\DataTypeTok{row.names =} \DecValTok{1}\NormalTok{,}\DataTypeTok{check.names =}\NormalTok{ F)}

\NormalTok{maxcol<-}\KeywordTok{apply}\NormalTok{(d1, }\DecValTok{2}\NormalTok{, max)}
\NormalTok{mincol<-}\KeywordTok{apply}\NormalTok{(d1, }\DecValTok{2}\NormalTok{, min)}

\NormalTok{d2<-}\KeywordTok{rbind}\NormalTok{(maxcol,mincol, d1)}
\KeywordTok{rownames}\NormalTok{(d2)[}\DecValTok{1}\OperatorTok{:}\DecValTok{2}\NormalTok{]<-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Max"}\NormalTok{, }\StringTok{"Min"}\NormalTok{)}

\KeywordTok{par}\NormalTok{(}\DataTypeTok{mar =} \KeywordTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{, }\FloatTok{0.1}\NormalTok{, }\DecValTok{4}\NormalTok{, }\FloatTok{0.1}\NormalTok{))}
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{4}\OperatorTok{:}\KeywordTok{nrow}\NormalTok{(d2)) \{}
  \KeywordTok{create_beautiful_radarchart}\NormalTok{(d2[}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{3}\NormalTok{, i), ],}\DataTypeTok{color =} \KeywordTok{c}\NormalTok{(}\StringTok{"#00AFBB"}\NormalTok{, }\StringTok{"#E7B800"}\NormalTok{,}\StringTok{"#FC4E07"}\NormalTok{),}\DataTypeTok{caxislabels =} \KeywordTok{seq}\NormalTok{(}\KeywordTok{round}\NormalTok{(}\KeywordTok{min}\NormalTok{(d2[}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{3}\NormalTok{, i),]),}\DecValTok{1}\NormalTok{),}\KeywordTok{round}\NormalTok{(}\KeywordTok{max}\NormalTok{(d2[}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{3}\NormalTok{, i),]),}\DecValTok{1}\NormalTok{),.}\DecValTok{2}\NormalTok{));}\KeywordTok{legend}\NormalTok{(}\DataTypeTok{x=}\FloatTok{0.4}\NormalTok{, }\DataTypeTok{y=}\FloatTok{1.4}\NormalTok{, }\DataTypeTok{legend =}\KeywordTok{c}\NormalTok{(}\StringTok{"unperturbed"}\NormalTok{,}\StringTok{"FVS perturbation"}\NormalTok{) , }\DataTypeTok{bty =} \StringTok{"n"}\NormalTok{, }\DataTypeTok{pch=}\DecValTok{20}\NormalTok{ , }\DataTypeTok{col=}\KeywordTok{c}\NormalTok{(}\StringTok{"#00AFBB"}\NormalTok{, }\StringTok{"#E7B800"}\NormalTok{,}\StringTok{"#FC4E07"}\NormalTok{) , }\DataTypeTok{text.col =} \StringTok{"black"}\NormalTok{, }\DataTypeTok{cex=}\DecValTok{1}\NormalTok{, }\DataTypeTok{pt.cex=}\DecValTok{2}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\includegraphics[width=0.5\linewidth]{_main_files/figure-latex/charts-1} \includegraphics[width=0.5\linewidth]{_main_files/figure-latex/charts-2} \includegraphics[width=0.5\linewidth]{_main_files/figure-latex/charts-3} \includegraphics[width=0.5\linewidth]{_main_files/figure-latex/charts-4} \includegraphics[width=0.5\linewidth]{_main_files/figure-latex/charts-5} \includegraphics[width=0.5\linewidth]{_main_files/figure-latex/charts-6} \includegraphics[width=0.5\linewidth]{_main_files/figure-latex/charts-7}

\hypertarget{pluripotent-stem-cell-example}{%
\chapter{Pluripotent Stem Cell Example}\label{pluripotent-stem-cell-example}}

This section contains instructions to reproduce the results of simulating perturbations on FVS control nodes in a pluripotent stem cell signaling. The goal of these simulations is to identify targets that can reprogram cells from the Epiblast stem cell (EpiSC) fate towards the Embryonic Stem Cell (ESC) fate. You can read the original report here: link

The input data, nextflow pipeline, and results of this simulation can be found in the \href{https://github.com/VeraLiconaResearchGroup/Netisce/tree/main/ipsc_validation}{ipsc folder} in the NETISCE github repository

\hypertarget{input-data-1}{%
\section{Input Data}\label{input-data-1}}

\href{https://github.com/VeraLiconaResearchGroup/Netisce/blob/main/ipsc_validation/input_data/network.sif}{\texttt{network.sif}} contains the network structure for pluripotent stem cell signaling

\href{https://github.com/VeraLiconaResearchGroup/Netisce/blob/main/ipsc_validation/input_data/expression.csv}{\texttt{expression.csv}} contains the initial activities for ESC cells (3 replicates), and EpiSC cells (3 replicates)

\href{https://github.com/VeraLiconaResearchGroup/Netisce/blob/main/ipsc_validation/input_data/internal-marker-kinoshita.txt}{\texttt{internal-marker-kinoshita.txt}} contains the 4 internal marker nodes that were originally used in Yachie-Kinoshita et al., to evaluate simulations.

\href{https://github.com/VeraLiconaResearchGroup/Netisce/blob/main/ipsc_validation/input_data/internal-marker-kinoshita-expanded.txt}{\texttt{internal-marker-kinoshita-expanded.txt}} contains the 4 internal marker nodes that were originally used in Yachie-Kinoshita et al., plus the additional marker ndoes identified from the data used to evaluate simulations.

\href{https://github.com/VeraLiconaResearchGroup/Netisce/blob/main/ipsc_validation/input_data/samples.txt}{\texttt{samples.txt}} contains they key for NETISCE to associate certain samples to the phenotypes of Embryonic Stem Cells (ESCs) or Epiblast Stem Cells (EpiSCs)

\hypertarget{run-the-simulation-1}{%
\section{Run the simulation}\label{run-the-simulation-1}}

These simulations were run on a high performance cluster that uses a SLURM executor. If your hpc uses a different executor, please update those specifications in the \texttt{nextflow.config} file in the directory. Please see \url{https://www.nextflow.io/docs/latest/config.html} for more information regarding your executor.

For ease of reproduction, we have included all files necessary to reproduce the reported results directly in the \href{https://github.com/VeraLiconaResearchGroup/Netisce/tree/main/ipsc_validation}{directory}. We do recommend you run this simulation on an hpc. We have included the \href{https://github.com/VeraLiconaResearchGroup/Netisce/blob/main/ipsc_validation/run.sh}{bash file} we used on our SLURM executor.

\textbf{Note: } within the \href{https://github.com/VeraLiconaResearchGroup/Netisce/blob/main/ipsc_validation/NETISCE.nf}{\texttt{NETISCE.nf}} configuration file, we have included two lines for specifying the internal-marker nodes:

\begin{verbatim}
#!/usr/bin/env nextflow

params.expressions = "$baseDir/input_data/expression.csv"
params.network = "$baseDir/input_data/network.sif"
params.samples = "$baseDir/input_data/samples.txt"
params.internal_control="$baseDir/input_data/internal-marker-kinoshita.txt"
// params.internal_control="$baseDir/input_data/internal-marker-kinoshita-expanded.txt"
params.alpha = 0.9
params.undesired = 'EpiSC'
params.desired = 'ESC'
params.filter ="strict"
\end{verbatim}

As discussed in our paper, we filtered the perturbations using the original 4 internal-marker nodes for pluripotency (Oct4, Sox2, Nanog, EpiTFs), and then again using 3 additional internal-marker nodes. Therefore, to run either analysis, comment/uncomment the internal-marker node file you are interested in. If you want to run NETISCE first with the original internal-marker nodes, make sure to change the results file names for \texttt{exp\_internalmarkers.txt},\texttt{successful\_controlnode\_perturubations.txt}, and \texttt{original-experimental\_internalmarkers.pdf} as to not overwrite them (or move them into a separate folder). Additionally, when you run the nextflow command, \textbf{please be sure to use the \texttt{-resume} flag so that you use the cached computations that do not need to be re-computed}

You can also run NETISCE directly using the following command: \texttt{./nextflow\ run\ NETISCE.nf\ -resume}

\hypertarget{results-1}{%
\section{Results}\label{results-1}}

Herein, we will focus on the results that are deposited in the \href{https://github.com/VeraLiconaResearchGroup/Netisce/tree/main/ipsc_validation/results}{\texttt{results}} folder by NETISCE. However, each step of the nextflow pipeline produces its corresponding raw results (for example, the entire attractor state for network simulations initialized with experimental data). If you are interested in looking at those raw results, they can be found within the \href{https://github.com/VeraLiconaResearchGroup/Netisce/tree/main/ipsc_validation/work}{\texttt{work}} folder. We provide \href{https://github.com/VeraLiconaResearchGroup/Netisce/blob/main/ipsc_validation/workfiles.txt}{\texttt{workfiles.txt}} which is a guide to which folders/subfolders contain the relevant results of each step.

\hypertarget{general-results}{%
\subsection{General Results}\label{general-results}}

First, let's take a look at the results that do not depend on the internal-marker node set.

\hypertarget{section-id}{%
\subsubsection*{FVS finding}\label{section-id}}
\addcontentsline{toc}{subsubsection}{FVS finding}

The FVS solving algorithm identified one FVS, containing 6 nodes.

\begin{tabular}{l}
\hline
name\\
\hline
Sox2\\
\hline
Nanog\\
\hline
Gata6\\
\hline
Tbx3\\
\hline
Oct4\\
\hline
Klf4\\
\hline
\end{tabular}

\hypertarget{section-id}{%
\subsubsection*{Attractor landscape estimation via k-means analysis}\label{section-id}}
\addcontentsline{toc}{subsubsection}{Attractor landscape estimation via k-means analysis}

Now, let's look at the results of k-means analysis. First, NETISCE determines the optimal number of k clusters by computing the elbow and silhouette metrics.

\begin{figure}
\includegraphics[width=0.5\linewidth]{ipsc/results/elbow} \includegraphics[width=0.5\linewidth]{ipsc/results/silhouette} \caption{optimal k as identified by a) the elbow and b) silhouette metrics}\label{fig:unnamed-chunk-25}
\end{figure}

We see that the optimal k assessed by the elbow metric was k=4, while the optimal k identified by the silhouette metric was k=2. NETISCE automatically chooses the smaller k value, after checking that the attractors generated from the ESC samples and EpiSC samples do not appear in the same cluster.

k=2 was selected for k-means optimal k, and we can see that the attractors generated from the ESC samples and EpiSC samples do not appear in separate clusters.

\begin{tabular}{l|r}
\hline
name & clusters\\
\hline
ESC\_1 & 0\\
\hline
ESC\_2 & 0\\
\hline
ESC\_3 & 0\\
\hline
EpiSC\_1 & 1\\
\hline
EpiSC\_2 & 1\\
\hline
EpiSC\_3 & 1\\
\hline
\end{tabular}

\hypertarget{section-id}{%
\subsubsection*{Pertrubations on FVS control nodes that pass criterion 1}\label{section-id}}
\addcontentsline{toc}{subsubsection}{Pertrubations on FVS control nodes that pass criterion 1}

With 6 FVS control nodes, NETISCE performed 729 simulations of combinations of perturbations on the FVS control nodes. The resulting attractors were classified to the clusters produced from the k-means analysis using Naive Bayes, Support Vector Machine, and Random Forest Machine Learning classification algorithms. Then, the perturbations are filtered by which of their corresponding attractors were classified to the ESC cluster by at least 2 of the 3 methods. These results can be found in \href{https://github.com/VeraLiconaResearchGroup/Netisce/blob/main/ipsc_validation/results/crit1perts.txt}{\texttt{crit1\_perts.txt}}. Here we show the first 10 rows.

\begin{verbatim}
## [1] "number of perturbations that pass filtering criteria 1: 375"
\end{verbatim}

\begin{tabular}{l}
\hline
x\\
\hline
pert\_8\\
\hline
pert\_17\\
\hline
pert\_26\\
\hline
pert\_35\\
\hline
pert\_44\\
\hline
pert\_53\\
\hline
pert\_88\\
\hline
pert\_89\\
\hline
pert\_97\\
\hline
pert\_98\\
\hline
\end{tabular}

\hypertarget{results-using-4-internal-marker-nodes}{%
\subsection{Results using 4 internal-marker nodes}\label{results-using-4-internal-marker-nodes}}

\textbf{The relevant files have the prefix `original' in the github repository}

Our second perturbation filtering criterion identifies perturbations where, in their corresponding attractors, 90\% of the steady state values for internal-marker nodes that are within the steady state expression ranges in the attractors generated from the ESC experimental data.

First, let's take a look at the steady state values of the internal-marker nodes Oct4, Sox2, and Nanog in the attractors generated from the ESC and EpiSC experimental data. The values can be found in the \href{https://github.com/VeraLiconaResearchGroup/Netisce/blob/main/ipsc_validation/results/original-exp_internalmarkers.txt}{\texttt{original-exp\_internalmarkers.txt}} and are plotted in \href{https://github.com/VeraLiconaResearchGroup/Netisce/blob/main/ipsc_validation/results/original-experimental_internalmarkers.pdf}{\texttt{original-experimental\_internalmarkers.pdf}}:

\begin{figure}[H]

{\centering \includegraphics[width=460pt,height=700pt]{ipsc/results/original-experimental_internalmarkers} 

}

\caption{histograms of 4 internal-marker node values}\label{fig:unnamed-chunk-28}
\end{figure}

We see that the values of the internal-markers for the pluripotent state (Oct4, Sox2, Nanog) are higher in the attractors generated from the experimental data of the ESCs than the attractors generated from the experimental data of the EpiSCs, and the makrer of the epiblast stem state is higher in the attractors generated from the experimental data of the EpiSCs than in the attractors generated from the experimental data of the ESC.

Now, we can take a look at the attractors that passed filtering criterion 2. We show the first 10 rows here, but you can view the entire set in \href{https://github.com/VeraLiconaResearchGroup/Netisce/blob/main/ipsc_validation/results/original-successful_controlnode_perturbations.txt}{\texttt{original-successful\_controlnode\_perturbations.txt}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{crit2_}\DecValTok{4}\NormalTok{<-}\KeywordTok{read.delim}\NormalTok{(}\StringTok{'ipsc/results/original-successful_controlnode_perturbations.txt'}\NormalTok{,}\DataTypeTok{sep=}\StringTok{" "}\NormalTok{,}\DataTypeTok{as.is =}\NormalTok{ T)}
\KeywordTok{print}\NormalTok{(}\KeywordTok{paste0}\NormalTok{(}\StringTok{'number of perturbations that pass filtering criteria 2: '}\NormalTok{,}\KeywordTok{nrow}\NormalTok{(crit2_}\DecValTok{4}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "number of perturbations that pass filtering criteria 2: 132"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{knitr}\OperatorTok{::}\KeywordTok{kable}\NormalTok{(crit2_}\DecValTok{4}\NormalTok{[}\DecValTok{1}\OperatorTok{:}\DecValTok{10}\NormalTok{,])  }\OperatorTok{%>%}\StringTok{ }\KeywordTok{column_spec}\NormalTok{(}\DecValTok{8}\NormalTok{, }\DataTypeTok{bold =}\NormalTok{ F, }\DataTypeTok{border_left =}\NormalTok{ T) }\OperatorTok{%>%}\StringTok{ }\KeywordTok{scroll_box}\NormalTok{(}\DataTypeTok{width =} \StringTok{"100%"}\NormalTok{, }\DataTypeTok{box_css =} \StringTok{"border: 0px;"}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\begin{tabular}{l|l|l|l|l|l|l||>{}r|r|r}
\hline
  & Sox2 & Nanog & Gata6 & Tbx3 & Oct4 & Klf4 & up & down & total\\
\hline
pert\_445 & nochange & up & nochange & nochange & nochange & nochange & 1 & 0 & 1\\
\hline
pert\_607 & up & nochange & nochange & nochange & nochange & nochange & 1 & 0 & 1\\
\hline
pert\_368 & nochange & nochange & nochange & nochange & up & up & 2 & 0 & 2\\
\hline
pert\_418 & nochange & up & down & nochange & nochange & nochange & 1 & 1 & 2\\
\hline
pert\_436 & nochange & up & nochange & down & nochange & nochange & 1 & 1 & 2\\
\hline
pert\_446 & nochange & up & nochange & nochange & nochange & up & 2 & 0 & 2\\
\hline
pert\_448 & nochange & up & nochange & nochange & up & nochange & 2 & 0 & 2\\
\hline
pert\_454 & nochange & up & nochange & up & nochange & nochange & 2 & 0 & 2\\
\hline
pert\_580 & up & nochange & down & nochange & nochange & nochange & 1 & 1 & 2\\
\hline
pert\_598 & up & nochange & nochange & down & nochange & nochange & 1 & 1 & 2\\
\hline
\end{tabular}

We can look to see if there are any trends in the orientation of the perturbations on FVS control nodes across the perturbations that passed both filtering criteria.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(data.table)}
\KeywordTok{library}\NormalTok{(ggplot2)}
\NormalTok{d3<-crit2_}\DecValTok{4}\NormalTok{ [,}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{6}\NormalTok{)] }\OperatorTok{%>%}\StringTok{ }\KeywordTok{transpose}\NormalTok{() }\OperatorTok{%>%}\StringTok{ }\KeywordTok{as.matrix}\NormalTok{()}
\KeywordTok{row.names}\NormalTok{(d3)<-}\KeywordTok{colnames}\NormalTok{(crit2_}\DecValTok{4}\NormalTok{[}\DecValTok{1}\OperatorTok{:}\DecValTok{6}\NormalTok{])}
\KeywordTok{colnames}\NormalTok{(d3)<-}\KeywordTok{row.names}\NormalTok{(crit2_}\DecValTok{4}\NormalTok{)}
\NormalTok{d3r<-reshape2}\OperatorTok{::}\KeywordTok{melt}\NormalTok{(d3) }\OperatorTok{%>%}\StringTok{ }\KeywordTok{select}\NormalTok{(}\OperatorTok{-}\NormalTok{Var2)}

\CommentTok{#From Paul Tol: https://personal.sron.nl/~pault/}
\NormalTok{Tol_muted <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{'#88CCEE'}\NormalTok{, }\StringTok{'#44AA99'}\NormalTok{, }\StringTok{'#117733'}\NormalTok{, }\StringTok{'#332288'}\NormalTok{, }\StringTok{'#DDCC77'}\NormalTok{, }\StringTok{'#999933'}\NormalTok{,}\StringTok{'#CC6677'}\NormalTok{, }\StringTok{'#882255'}\NormalTok{, }\StringTok{'#AA4499'}\NormalTok{, }\StringTok{'#DDDDDD'}\NormalTok{)}

\KeywordTok{ggplot}\NormalTok{(d3r, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{value)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{Var1,}\DataTypeTok{scales =} \StringTok{"free_x"}\NormalTok{,}\DataTypeTok{shrink=}\OtherTok{FALSE}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ (..count..)}\OperatorTok{/}\KeywordTok{ncol}\NormalTok{(d3),}\DataTypeTok{fill=}\NormalTok{value))  }\OperatorTok{+}\StringTok{ }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{labels=}\NormalTok{scales}\OperatorTok{::}\NormalTok{percent) }\OperatorTok{+}\StringTok{ }\KeywordTok{scale_fill_manual}\NormalTok{(}\DataTypeTok{values=}\NormalTok{Tol_muted)}\OperatorTok{+}\StringTok{ }\KeywordTok{ylab}\NormalTok{(}\StringTok{"% of specified perturbation to an FVS control node across all }\CharTok{\textbackslash{}n}\StringTok{ combinations of perturbations that passed filtering criteria "}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{xlab}\NormalTok{(}\StringTok{"node perturbation"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{_main_files/figure-latex/unnamed-chunk-30-1} \end{center}

Here, we see that in the majority of perturbations, there is overexpression of the FVS nodes Sox2, Nanog and Oct4. This aligns with their role as maintainers of pluripotency.

The steady-state values of the internal-marker nodes for these perturbations can be found in \href{https://github.com/VeraLiconaResearchGroup/Netisce/blob/main/ipsc_validation/results/pert1_internal_markers.txt}{\texttt{pert1\_internal\_markers.txt}}.

A perturbation on the FVS control node, Nanog overexpression (pert\_445), was also identified in Yachie-Kinoshita et al.~and experimentally verified to shift cells from the EpiSC state towards the ESC state. We can plot the internal-marker node values using a radar plot.

We can also plot Klf4 overexpression. This was a perturbation identified by Yachie-Kinoshita et al.~to shift cells from the EpiSC state towards the ESC state. However, in our analyses, this perturbation (pert\_365), did pass filtering criterion 1, but did not pass filtering criterion 2.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(fmsb)}
\NormalTok{attr_pert<-}\KeywordTok{read.delim}\NormalTok{(}\StringTok{"ipsc/results/pert1_internal_markers.txt"}\NormalTok{,}\DataTypeTok{sep=}\StringTok{" "}\NormalTok{,}\DataTypeTok{row.names =} \DecValTok{1}\NormalTok{)}
\NormalTok{attr_pert <-attr_pert[}\KeywordTok{c}\NormalTok{(}\StringTok{'pert_445'}\NormalTok{,}\StringTok{'pert_365'}\NormalTok{),}\KeywordTok{c}\NormalTok{(}\StringTok{'Oct4'}\NormalTok{,}\StringTok{"Sox2"}\NormalTok{,}\StringTok{"Nanog"}\NormalTok{,}\StringTok{"EpiTFs"}\NormalTok{)]}
\NormalTok{exp<-}\KeywordTok{read.delim}\NormalTok{(}\StringTok{"ipsc/results/original-exp_internalmarkers.txt"}\NormalTok{,}\DataTypeTok{sep=}\StringTok{" "}\NormalTok{,}\DataTypeTok{row.names =} \DecValTok{1}\NormalTok{)}
\NormalTok{EpiSC_avg<-}\KeywordTok{colMeans}\NormalTok{(exp[}\DecValTok{4}\OperatorTok{:}\DecValTok{6}\NormalTok{,])}
\NormalTok{ESC_avg<-}\KeywordTok{colMeans}\NormalTok{(exp[}\DecValTok{1}\OperatorTok{:}\DecValTok{3}\NormalTok{,])}

\NormalTok{d1<-}\KeywordTok{rbind}\NormalTok{(EpiSC_avg,ESC_avg,attr_pert)}
\KeywordTok{rownames}\NormalTok{(d1)[}\DecValTok{1}\OperatorTok{:}\DecValTok{4}\NormalTok{]<-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"EpiSC"}\NormalTok{, }\StringTok{"ESC"}\NormalTok{,}\StringTok{"Nanog overexpression"}\NormalTok{,}\StringTok{"Klf4 overexpression"}\NormalTok{)}
\NormalTok{maxcol<-}\KeywordTok{apply}\NormalTok{(d1, }\DecValTok{2}\NormalTok{, max)}
\NormalTok{mincol<-}\KeywordTok{apply}\NormalTok{(d1, }\DecValTok{2}\NormalTok{, min)}

\NormalTok{d2<-}\KeywordTok{rbind}\NormalTok{(maxcol,mincol, d1)}
\KeywordTok{rownames}\NormalTok{(d2)[}\DecValTok{1}\OperatorTok{:}\DecValTok{2}\NormalTok{]<-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Max"}\NormalTok{, }\StringTok{"Min"}\NormalTok{)}

\KeywordTok{par}\NormalTok{(}\DataTypeTok{mar =} \KeywordTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{, }\FloatTok{0.1}\NormalTok{, }\DecValTok{4}\NormalTok{, }\FloatTok{0.1}\NormalTok{))}


\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{5}\OperatorTok{:}\KeywordTok{nrow}\NormalTok{(d2)) \{}
  \KeywordTok{create_beautiful_radarchart}\NormalTok{(d2[}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{4}\NormalTok{, i), ],}\DataTypeTok{color =} \KeywordTok{c}\NormalTok{(}\StringTok{"#00AFBB"}\NormalTok{, }\StringTok{"#E7B800"}\NormalTok{,}\StringTok{"#FC4E07"}\NormalTok{),}\DataTypeTok{caxislabels =} \KeywordTok{seq}\NormalTok{(}\KeywordTok{round}\NormalTok{(}\KeywordTok{min}\NormalTok{(d2[}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{4}\NormalTok{, i),]),}\DecValTok{1}\NormalTok{),}\KeywordTok{round}\NormalTok{(}\KeywordTok{max}\NormalTok{(d2[}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{4}\NormalTok{, i),]),}\DecValTok{1}\NormalTok{),.}\DecValTok{2}\NormalTok{),}\DataTypeTok{title =}\KeywordTok{row.names}\NormalTok{(d2)[i]);}\KeywordTok{legend}\NormalTok{(}\DataTypeTok{x=}\FloatTok{0.4}\NormalTok{, }\DataTypeTok{y=}\FloatTok{1.4}\NormalTok{, }\DataTypeTok{legend =}\KeywordTok{c}\NormalTok{(}\StringTok{"average EpiSC"}\NormalTok{,}\StringTok{"average ESC"}\NormalTok{,}\KeywordTok{row.names}\NormalTok{(d2)[i]) , }\DataTypeTok{bty =} \StringTok{"n"}\NormalTok{, }\DataTypeTok{pch=}\DecValTok{20}\NormalTok{ , }\DataTypeTok{col=}\KeywordTok{c}\NormalTok{(}\StringTok{"#00AFBB"}\NormalTok{, }\StringTok{"#E7B800"}\NormalTok{,}\StringTok{"#FC4E07"}\NormalTok{) , }\DataTypeTok{text.col =} \StringTok{"black"}\NormalTok{, }\DataTypeTok{cex=}\DecValTok{1}\NormalTok{, }\DataTypeTok{pt.cex=}\DecValTok{2}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\includegraphics[width=0.5\linewidth]{_main_files/figure-latex/ipsc-charts-1} \includegraphics[width=0.5\linewidth]{_main_files/figure-latex/ipsc-charts-2} \caption{radar charts of the steady-state values of 4 internal-marker nodes for Nanog overexpression and Klf4 overexpression perturbation}\label{fig:ipsc-charts}
\end{figure}

We see here, indeed that the values for Oct4, Sox2, Nanog, (when considered these three genes as internal-marker nodes) and EpiTFs are within the expected range for Nanog overexpression, but the values of Oct4, Sox2, Nanog in the attractor generated from Klf4 overexpression do not reach the values of the ESC state.

\hypertarget{results-using-7-internal-marker-nodes}{%
\subsection{Results using 7 internal-marker nodes}\label{results-using-7-internal-marker-nodes}}

\emph{The relevant files have the prefix `expanded' in the github repository.}

We explored filtering the 132 perturbations that passed the second filtering criterion by adding additional internal-marker nodes associated with pluripotency. We added 3 nodes, Lefty1, Pitx2 (transcription factors active in EpiSCs), and Esrrb (transcription factor active in ESCs) to the 4 previously used internal-marker nodes.

Let's look at the steady state values of the internal-marker nodes in the attractors generated from the ESC and EpiSC experimental data. The values can be found in the \href{https://github.com/VeraLiconaResearchGroup/Netisce/blob/main/ipsc_validation/results/expanded-exp_internalmarkers.txt}{\texttt{expanded-exp\_internalmarkers.txt}} and are plotted in \href{https://github.com/VeraLiconaResearchGroup/Netisce/blob/main/ipsc_validation/results/expanded-experimental_internalmarkers.pdf}{\texttt{expanded-experimental\_internalmarkers.pdf}}:

\begin{figure}[H]

{\centering \includegraphics[width=460pt,height=700pt]{ipsc/results/expanded-experimental_internalmarkers} 

}

\caption{histograms of 7 internal-marker node values}\label{fig:unnamed-chunk-31}
\end{figure}

Again, the internal-marker nodes have the correct expression patterns within the attractors generated from the ESC and EpiSC states.

Now, we can take a look at the attractors that passed filtering criterion 2. These are in file \href{https://github.com/VeraLiconaResearchGroup/Netisce/blob/main/ipsc_validation/results/expanded-successful_controlnode_perturbations.txt}{\texttt{expanded-successful\_controlnode\_perturbations.txt}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{crit2_}\DecValTok{7}\NormalTok{<-}\KeywordTok{read.delim}\NormalTok{(}\StringTok{'ipsc/results/expanded-successful_controlnode_perturbations.txt'}\NormalTok{,}\DataTypeTok{sep=}\StringTok{" "}\NormalTok{)}
\KeywordTok{print}\NormalTok{(}\KeywordTok{paste0}\NormalTok{(}\StringTok{'number of perturbations that pass filtering criteria 2: '}\NormalTok{,}\KeywordTok{nrow}\NormalTok{(crit2_}\DecValTok{7}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "number of perturbations that pass filtering criteria 2: 15"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{knitr}\OperatorTok{::}\KeywordTok{kable}\NormalTok{(crit2_}\DecValTok{7}\NormalTok{)  }\OperatorTok{%>%}\StringTok{ }\KeywordTok{column_spec}\NormalTok{(}\DecValTok{8}\NormalTok{, }\DataTypeTok{bold =}\NormalTok{ F, }\DataTypeTok{border_left =}\NormalTok{ T) }\OperatorTok{%>%}\StringTok{ }\KeywordTok{scroll_box}\NormalTok{(}\DataTypeTok{width =} \StringTok{"100%"}\NormalTok{, }\DataTypeTok{box_css =} \StringTok{"border: 0px;"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{tabular}{l|l|l|l|l|l|l||>{}r|r|r}
\hline
  & Sox2 & Nanog & Gata6 & Tbx3 & Oct4 & Klf4 & up & down & total\\
\hline
pert\_445 & nochange & up & nochange & nochange & nochange & nochange & 1 & 0 & 1\\
\hline
pert\_418 & nochange & up & down & nochange & nochange & nochange & 1 & 1 & 2\\
\hline
pert\_436 & nochange & up & nochange & down & nochange & nochange & 1 & 1 & 2\\
\hline
pert\_446 & nochange & up & nochange & nochange & nochange & up & 2 & 0 & 2\\
\hline
pert\_454 & nochange & up & nochange & up & nochange & nochange & 2 & 0 & 2\\
\hline
pert\_409 & nochange & up & down & down & nochange & nochange & 1 & 2 & 3\\
\hline
pert\_419 & nochange & up & down & nochange & nochange & up & 2 & 1 & 3\\
\hline
pert\_427 & nochange & up & down & up & nochange & nochange & 2 & 1 & 3\\
\hline
pert\_437 & nochange & up & nochange & down & nochange & up & 2 & 1 & 3\\
\hline
pert\_455 & nochange & up & nochange & up & nochange & up & 3 & 0 & 3\\
\hline
pert\_473 & nochange & up & up & nochange & nochange & up & 3 & 0 & 3\\
\hline
pert\_410 & nochange & up & down & down & nochange & up & 2 & 2 & 4\\
\hline
pert\_428 & nochange & up & down & up & nochange & up & 3 & 1 & 4\\
\hline
pert\_464 & nochange & up & up & down & nochange & up & 3 & 1 & 4\\
\hline
pert\_482 & nochange & up & up & up & nochange & up & 4 & 0 & 4\\
\hline
\end{tabular}

We can plot the trends of the orientation of perturbations for each FVS control node across the 15 perturbations.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{d4<-crit2_}\DecValTok{7}\NormalTok{ [,}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{6}\NormalTok{)] }\OperatorTok{%>%}\StringTok{ }\KeywordTok{transpose}\NormalTok{() }\OperatorTok{%>%}\StringTok{ }\KeywordTok{as.matrix}\NormalTok{()}
\KeywordTok{row.names}\NormalTok{(d4)<-}\KeywordTok{colnames}\NormalTok{(crit2_}\DecValTok{7}\NormalTok{[}\DecValTok{1}\OperatorTok{:}\DecValTok{6}\NormalTok{])}
\KeywordTok{colnames}\NormalTok{(d4)<-}\KeywordTok{row.names}\NormalTok{(crit2_}\DecValTok{7}\NormalTok{)}
\NormalTok{d4r<-reshape2}\OperatorTok{::}\KeywordTok{melt}\NormalTok{(d4) }\OperatorTok{%>%}\StringTok{ }\KeywordTok{select}\NormalTok{(}\OperatorTok{-}\NormalTok{Var2)}



\KeywordTok{ggplot}\NormalTok{(d4r, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{value)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{Var1,}\DataTypeTok{scales =} \StringTok{"free_x"}\NormalTok{,}\DataTypeTok{shrink=}\OtherTok{FALSE}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ (..count..)}\OperatorTok{/}\KeywordTok{ncol}\NormalTok{(d4),}\DataTypeTok{fill=}\NormalTok{value))  }\OperatorTok{+}\StringTok{ }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{labels=}\NormalTok{scales}\OperatorTok{::}\NormalTok{percent) }\OperatorTok{+}\StringTok{ }\KeywordTok{scale_fill_manual}\NormalTok{(}\DataTypeTok{values=}\NormalTok{Tol_muted) }\OperatorTok{+}\StringTok{ }\KeywordTok{ylab}\NormalTok{(}\StringTok{"% of specified perturbation to an FVS control node across all }\CharTok{\textbackslash{}n}\StringTok{ combinations of perturbations that passed filtering criteria "}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{xlab}\NormalTok{(}\StringTok{"node perturbation"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{_main_files/figure-latex/unnamed-chunk-33-1} \end{center}

Interestingly, we see among these 15 perturbations, Nanog overexpression, but no change to Oct4 or Sox2, is indicated. We also see that Klf4 is overexpressed in the majority of these 15 perturbations.

The steady-state values of the internal-marker nodes for these perturbations can be found in \href{https://github.com/VeraLiconaResearchGroup/Netisce/blob/main/ipsc_validation/results/pert1_internal_markers.txt}{\texttt{pert1\_internal\_markers.txt}}.

We can also generate radar plots for these 15 perturbations.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(fmsb)}
\NormalTok{attr_pert<-}\KeywordTok{read.delim}\NormalTok{(}\StringTok{"ipsc/results/pert1_internal_markers.txt"}\NormalTok{,}\DataTypeTok{sep=}\StringTok{" "}\NormalTok{,}\DataTypeTok{row.names =} \DecValTok{1}\NormalTok{)}
\NormalTok{attr_pert <-attr_pert[}\KeywordTok{row.names}\NormalTok{(crit2_}\DecValTok{7}\NormalTok{),]}
\NormalTok{exp<-}\KeywordTok{read.delim}\NormalTok{(}\StringTok{"ipsc/results/expanded-exp_internalmarkers.txt"}\NormalTok{,}\DataTypeTok{sep=}\StringTok{" "}\NormalTok{,}\DataTypeTok{row.names =} \DecValTok{1}\NormalTok{)}
\NormalTok{EpiSC_avg<-}\KeywordTok{colMeans}\NormalTok{(exp[}\DecValTok{4}\OperatorTok{:}\DecValTok{6}\NormalTok{,])}
\NormalTok{ESC_avg<-}\KeywordTok{colMeans}\NormalTok{(exp[}\DecValTok{1}\OperatorTok{:}\DecValTok{3}\NormalTok{,])}

\NormalTok{d1<-}\KeywordTok{rbind}\NormalTok{(EpiSC_avg,ESC_avg,attr_pert)}
\KeywordTok{rownames}\NormalTok{(d1)[}\DecValTok{1}\OperatorTok{:}\DecValTok{2}\NormalTok{]<-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"EpiSC"}\NormalTok{, }\StringTok{"ESC"}\NormalTok{)}
\NormalTok{maxcol<-}\KeywordTok{apply}\NormalTok{(d1, }\DecValTok{2}\NormalTok{, max)}
\NormalTok{mincol<-}\KeywordTok{apply}\NormalTok{(d1, }\DecValTok{2}\NormalTok{, min)}

\NormalTok{d2<-}\KeywordTok{rbind}\NormalTok{(maxcol,mincol, d1)}
\KeywordTok{rownames}\NormalTok{(d2)[}\DecValTok{1}\OperatorTok{:}\DecValTok{2}\NormalTok{]<-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Max"}\NormalTok{, }\StringTok{"Min"}\NormalTok{)}

\KeywordTok{par}\NormalTok{(}\DataTypeTok{mar =} \KeywordTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{, }\FloatTok{0.1}\NormalTok{, }\DecValTok{4}\NormalTok{, }\FloatTok{0.1}\NormalTok{))}

\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{5}\OperatorTok{:}\KeywordTok{nrow}\NormalTok{(d2)) \{}
  \KeywordTok{create_beautiful_radarchart}\NormalTok{(d2[}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{4}\NormalTok{, i), ],}\DataTypeTok{color =} \KeywordTok{c}\NormalTok{(}\StringTok{"#00AFBB"}\NormalTok{, }\StringTok{"#E7B800"}\NormalTok{,}\StringTok{"#FC4E07"}\NormalTok{),}\DataTypeTok{caxislabels =} \KeywordTok{seq}\NormalTok{(}\KeywordTok{round}\NormalTok{(}\KeywordTok{min}\NormalTok{(d2[}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{4}\NormalTok{, i),]),}\DecValTok{1}\NormalTok{),}\KeywordTok{round}\NormalTok{(}\KeywordTok{max}\NormalTok{(d2[}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{4}\NormalTok{, i),]),}\DecValTok{1}\NormalTok{),.}\DecValTok{2}\NormalTok{),}\DataTypeTok{title =}\KeywordTok{row.names}\NormalTok{(d2)[i]);}\KeywordTok{legend}\NormalTok{(}\DataTypeTok{x=}\FloatTok{0.4}\NormalTok{, }\DataTypeTok{y=}\FloatTok{1.4}\NormalTok{, }\DataTypeTok{legend =}\KeywordTok{c}\NormalTok{(}\StringTok{"average EpiSC"}\NormalTok{,}\StringTok{"average ESC"}\NormalTok{,}\KeywordTok{row.names}\NormalTok{(d2)[i]) , }\DataTypeTok{bty =} \StringTok{"n"}\NormalTok{, }\DataTypeTok{pch=}\DecValTok{20}\NormalTok{ , }\DataTypeTok{col=}\KeywordTok{c}\NormalTok{(}\StringTok{"#00AFBB"}\NormalTok{, }\StringTok{"#E7B800"}\NormalTok{,}\StringTok{"#FC4E07"}\NormalTok{) , }\DataTypeTok{text.col =} \StringTok{"black"}\NormalTok{, }\DataTypeTok{cex=}\DecValTok{1}\NormalTok{, }\DataTypeTok{pt.cex=}\DecValTok{2}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\includegraphics[width=0.5\linewidth]{_main_files/figure-latex/ipsc-charts2-1} \includegraphics[width=0.5\linewidth]{_main_files/figure-latex/ipsc-charts2-2} \includegraphics[width=0.5\linewidth]{_main_files/figure-latex/ipsc-charts2-3} \includegraphics[width=0.5\linewidth]{_main_files/figure-latex/ipsc-charts2-4} \includegraphics[width=0.5\linewidth]{_main_files/figure-latex/ipsc-charts2-5} \includegraphics[width=0.5\linewidth]{_main_files/figure-latex/ipsc-charts2-6} \includegraphics[width=0.5\linewidth]{_main_files/figure-latex/ipsc-charts2-7} \includegraphics[width=0.5\linewidth]{_main_files/figure-latex/ipsc-charts2-8} \includegraphics[width=0.5\linewidth]{_main_files/figure-latex/ipsc-charts2-9} \includegraphics[width=0.5\linewidth]{_main_files/figure-latex/ipsc-charts2-10} \includegraphics[width=0.5\linewidth]{_main_files/figure-latex/ipsc-charts2-11} \includegraphics[width=0.5\linewidth]{_main_files/figure-latex/ipsc-charts2-12} \includegraphics[width=0.5\linewidth]{_main_files/figure-latex/ipsc-charts2-13} \includegraphics[width=0.5\linewidth]{_main_files/figure-latex/ipsc-charts2-14} \includegraphics[width=0.5\linewidth]{_main_files/figure-latex/ipsc-charts2-15} \caption{radar charts of the steady-state values of 7 internal-marker nodes perturbation}\label{fig:ipsc-charts2}
\end{figure}

These radar plots show that for all 15 perturbations on FVS control nodes, the steady-state values of the internal-marker nodes are within the expression range of the attractors generated from the ESC experimental data.

\hypertarget{adaptive-resistance-in-colorectal-cancer-example}{%
\chapter{Adaptive Resistance in Colorectal Cancer Example}\label{adaptive-resistance-in-colorectal-cancer-example}}

This section contains instructions to reproduce the results of simulating perturbations on FVS control nodes in a network of colorectal cancer (CRC) signaling pathways. The goal of these simulations is to identify targets that can reprogram cells from a MAPK inhibitor therapy resistant phenotype to the MAPK inhibitor therapy sensitive fate. You can read the original report here: link

The input data, nextflow pipeline, and results of this simulation can be found in the \href{https://github.com/VeraLiconaResearchGroup/Netisce/tree/main/colorectal_cancer_validation}{colorectal\_cancer\_validation folder} in the NETISCE github repository

\hypertarget{input-data-2}{%
\section{Input Data}\label{input-data-2}}

\href{https://github.com/VeraLiconaResearchGroup/Netisce/blob/main/colorectal_cancer_validation/input_data/network.sif}{\texttt{network.sif}} contains the network structure for CRC signaling

\href{https://github.com/VeraLiconaResearchGroup/Netisce/blob/main/colorectal_cancer_validation/input_data/expression.csv}{\texttt{expression.csv}} contains the initial activities for HT29 untreated cells. The columns for H29\_BRAFi (MAPK inhibitor therapy resistant state) and H29\_BRAFi+EGRFi (MAPK inhibitor therapy sensitive state) are copies of the HT29 column

\href{https://github.com/VeraLiconaResearchGroup/Netisce/blob/main/colorectal_cancer_validation/input_data/internal-marker-1.txt}{\texttt{internal-marker-1.txt}} contains the 3 internal marker nodes that were originally used in Park et al., to evaluate simulations.

\href{https://github.com/VeraLiconaResearchGroup/Netisce/blob/main/colorectal_cancer_validation/input_data/internal-marker-apoptosis.txt}{\texttt{internal-marker-apoptosis.txt}} contains the internal marker nodes related to apoptosis used to evaluate simulations.

\href{https://github.com/VeraLiconaResearchGroup/Netisce/blob/main/colorectal_cancer_validation/input_data/internal-marker-mapk.txt}{\texttt{internal-marker-mapk.txt}} contains the internal marker nodes related to mapk used to evaluate simulations.

\href{https://github.com/VeraLiconaResearchGroup/Netisce/blob/main/colorectal_cancer_validation/input_data/internal-marker-proliferation.txt}{\texttt{internal-marker-proliferation.txt}} contains the internal marker nodes related to proliferation used to evaluate simulations.

\href{https://github.com/VeraLiconaResearchGroup/Netisce/blob/main/colorectal_cancer_validation/input_data/samples.txt}{\texttt{samples.txt}} contains they key for NETISCE to associate certain samples to the phenotypes of untreated (HT29), resistant (HT29\_BRAFi), and sensitive (HT29\_BRAFiEGFRi)

\href{https://github.com/VeraLiconaResearchGroup/Netisce/blob/main/colorectal_cancer_validation/input_data/mutations.csv}{\texttt{mutations.csv}} mutational profile of HT29 cells, as well as the overrides for simulating BRAFi and EGRFi.

\hypertarget{run-the-simulation-2}{%
\section{Run the simulation}\label{run-the-simulation-2}}

These simulations were run on a high performance cluster that uses a SLURM executor. If your hpc uses a different executor, please update those specifications in the \texttt{nextflow.config} file in the directory. Please see \url{https://www.nextflow.io/docs/latest/config.html} for more information regarding your executor.

For ease of reproduction, we have included all files necessary to reproduce the reported results directly in the \href{https://github.com/VeraLiconaResearchGroup/Netisce/tree/main/colorectal_cancer_validation}{directory}. We highly recommend you run this simulation on an hpc, as you will be generating files of 3Gb+. We have included the \href{https://github.com/VeraLiconaResearchGroup/Netisce/blob/main/colorectal_cancer_validation/run.sh}{bash file} we used on our SLURM executor.

\textbf{Note: } within the \href{https://github.com/VeraLiconaResearchGroup/Netisce/blob/main/colorectal_cancer_validation/NETISCE_mutations.nf}{\texttt{NETISCE\_mutations.nf}} configuration file, you will want to change the params.internal\_control line if you want to use a different set of internal-marker nodes.

\begin{verbatim}
#!/usr/bin/env nextflow

params.expressions = "$baseDir/input_data/expression.csv"
params.network = "$baseDir/input_data/network.sif"
params.samples = "$baseDir/input_data/samples.txt"
params.internal_control="$baseDir/input_data/internal-marker-1.txt"
params.mutations="$baseDir/input_data/mutations.csv"
params.alpha = 0.9
params.undesired = 'resistant'
params.desired = 'sensitive'
params.filter ="strict"
\end{verbatim}

As discussed in our paper, we filtered the perturbations using the original 3 internal-marker nodes for apoptosis, proliferation, and MAPK signaling. We further filtered perturbations on the FVS control nodes using 17 addition internal-marker nodes, related to the phenotypes of apoptosis, proliferation, and MAPK signaling. Therefore, to use a set of internal-marker nodes, please point to the correct input-data file. We created folders within the \texttt{results} folder to house the relevant internal-marker node files for each set. You may want to do the same as to not overwrite them (or move them into a separate folder). Additionally, when you run the nextflow command, \textbf{please be sure to use the \texttt{-resume} flag so that you use the cached computations that do not need to be re-computed}

You can run NETISCE directly from this folder using the following command: \texttt{./nextflow\ run\ NETISC\_mutations.nf\ -resume}

\hypertarget{results-2}{%
\section{Results}\label{results-2}}

Herein, we will focus on the results that are deposited in the \href{https://github.com/VeraLiconaResearchGroup/Netisce/tree/main/colorectal_cancer_validation/results}{\texttt{results}} folder by NETISCE. However, each step of the nextflow pipeline produces its corresponding raw results (for example, the entire attractor state for network simulations initialized with experimental data). If you are interested in looking at those raw results, they can be found within the \href{https://github.com/VeraLiconaResearchGroup/Netisce/tree/main/colorectal_cancer_validation/work}{\texttt{work}} folder. We provide \href{https://github.com/VeraLiconaResearchGroup/Netisce/blob/main/colorectal_cancer_validation/work/workfiles.txt}{\texttt{workfiles.txt}} which is a guide to which folders/subfolders contain the relevant results of each step.

\hypertarget{general-results-1}{%
\subsection{General Results}\label{general-results-1}}

First, let's take a look at the results that do not depend on the internal-marker node set.

\hypertarget{section-id}{%
\subsubsection*{FVS finding}\label{section-id}}
\addcontentsline{toc}{subsubsection}{FVS finding}

Here we focus on one of the FVSes in the network, which we call, Set 1.

\begin{tabular}{l}
\hline
name\\
\hline
AKT1\\
\hline
CCNA1\\
\hline
CTNNB1\\
\hline
E2F1\\
\hline
GRB2\\
\hline
MAPK1\\
\hline
MAPK14\\
\hline
MAPK8\\
\hline
MDM2\\
\hline
PDK1\\
\hline
SMAD7\\
\hline
SRC\\
\hline
TP53\\
\hline
TSC1\\
\hline
\end{tabular}

Set 1 contains 14 nodes. Notice that TP53 is included in the FVS. This is a mutant gene in HT29 cells. NETISCE\_mutations automatically filters out mutated genes, and places the FVS without mutated genes in the \texttt{fvs-no-mutated-genes.txt} file.

and we remove mutated genes!

\begin{tabular}{l}
\hline
name\\
\hline
AKT1\\
\hline
CCNA1\\
\hline
CTNNB1\\
\hline
E2F1\\
\hline
GRB2\\
\hline
MAPK1\\
\hline
MAPK14\\
\hline
MAPK8\\
\hline
MDM2\\
\hline
PDK1\\
\hline
SMAD7\\
\hline
SRC\\
\hline
TSC1\\
\hline
\end{tabular}

\hypertarget{section-id}{%
\subsubsection*{Attractor landscape estimation via k-means analysis}\label{section-id}}
\addcontentsline{toc}{subsubsection}{Attractor landscape estimation via k-means analysis}

Now, let's look at the results of k-means analysis. First, NETISCE determines the optimal number of k clusters by computing the elbow and silhouette metrics.

\begin{figure}
\includegraphics[width=0.5\linewidth]{crc/results/elbow} \includegraphics[width=0.5\linewidth]{crc/results/silhouette} \caption{optimal k as identified by a) the elbow and b) silhouette metrics}\label{fig:unnamed-chunk-36}
\end{figure}

We see that the optimal k assessed by both the elbow metric and silhouette metric was k=3. NETISCE checkes to make sure that the untreated, MAPK inihibitor therapy resistant, and MAPK inhibitor therapy sensitive attractors are all separate.

We can look at those results in the \texttt{kmeans.txt} file.

\begin{tabular}{l|r}
\hline
name & clusters\\
\hline
HT29 & 0\\
\hline
HT29\_BRAFiEGFRi & 2\\
\hline
HT29\_BRAFi & 1\\
\hline
\end{tabular}

\hypertarget{section-id}{%
\subsubsection*{Pertrubations on FVS control nodes that pass criterion 1}\label{section-id}}
\addcontentsline{toc}{subsubsection}{Pertrubations on FVS control nodes that pass criterion 1}

With 13 FVS control nodes, NETISCE performed 1,594,323 simulations of combinations of perturbations on the FVS control nodes. The resulting attractors were classified to the clusters produced from the k-means analysis using Naive Bayes, Support Vector Machine, and Random Forest Machine Learning classification algorithms. Then, the perturbations are filtered by which of their corresponding attractors were classified to the MAPK inhibitor therapy sensitive cluster by at least 2 of the 3 methods. These results can be found in \href{https://github.com/VeraLiconaResearchGroup/Netisce/blob/main/colorectal_cancer_validation/results/crit1perts.txt}{\texttt{crit1\_perts.txt}}. Here we show the first 10 rows.

\begin{verbatim}
## [1] "number of perturbations that pass filtering criteria 1: 232114"
\end{verbatim}

\begin{tabular}{l}
\hline
x\\
\hline
pert\_0\\
\hline
pert\_1\\
\hline
pert\_2\\
\hline
pert\_9\\
\hline
pert\_10\\
\hline
pert\_11\\
\hline
pert\_18\\
\hline
pert\_19\\
\hline
pert\_20\\
\hline
pert\_27\\
\hline
\end{tabular}

\hypertarget{results-using-3-internal-marker-nodes}{%
\subsection{Results using 3 internal-marker nodes}\label{results-using-3-internal-marker-nodes}}

\textbf{The relevant files have the prefix `original' in the github repository}

Our second perturbation filtering criterion identifies perturbations where, in their corresponding attractors, 90\% of the steady state values for internal-marker nodes that are within the steady state expression ranges in the attractor representing MAPK inhibitor therapy sensitivity.

First, let's take a look at the steady state values of the internal-marker nodes CASP3, CCNE1, and MAPK1 in the attractors generated from the untreated HT29 with simulated BRAFi (resistant) and BRAFi+EGFRi (sensitive). The values can be found in the \href{https://github.com/VeraLiconaResearchGroup/Netisce/blob/main/colorectal_cancer_validation/results/3-marker-nodes/exp_internalmarkers.txt}{\texttt{exp\_internalmarkers.txt}} and are plotted in \href{https://github.com/VeraLiconaResearchGroup/Netisce/blob/main/colorectal_cancer_validation/results/3-marker-nodes/experimental_internalmarkers.pdf}{\texttt{-experimental\_internalmarkers.pdf}}:

\begin{figure}[H]

{\centering \includegraphics[width=9.72in]{crc/results/3-marker-nodes/experimental_internalmarkers} 

}

\caption{histograms of 3 internal-marker node values}\label{fig:unnamed-chunk-39}
\end{figure}

We see that the value of the internal-marker for the apoptosis (CASP3) is higher and the steady-state values of the internal-marker nodes for proliferation (CCNE1) and MAPK signaling (MAPK1) are lower in the MAPK inhibitor therapy sensitive associated attractor than the MAPK inhibitor therapy resistance and untreated associated attractors.

Now, we can take a look at the attractors that passed filtering criterion 2. We show the first 10 rows here, but you can view the entire set in \href{https://github.com/VeraLiconaResearchGroup/Netisce/blob/main/colorectal_cancer_validation/results/3-marker-nodes/successful_controlnode_perturbations.txt}{\texttt{successful\_controlnode\_perturbations.txt}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{crit2_}\DecValTok{3}\NormalTok{<-}\KeywordTok{read.delim}\NormalTok{(}\StringTok{'crc/results/3-marker-nodes/successful_controlnode_perturbations.txt'}\NormalTok{,}\DataTypeTok{sep=}\StringTok{" "}\NormalTok{,}\DataTypeTok{as.is =}\NormalTok{ T)}
\KeywordTok{print}\NormalTok{(}\KeywordTok{paste0}\NormalTok{(}\StringTok{'number of perturbations that pass filtering criteria 2: '}\NormalTok{,}\KeywordTok{nrow}\NormalTok{(crit2_}\DecValTok{3}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "number of perturbations that pass filtering criteria 2: 52703"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{knitr}\OperatorTok{::}\KeywordTok{kable}\NormalTok{(crit2_}\DecValTok{3}\NormalTok{[}\DecValTok{1}\OperatorTok{:}\DecValTok{10}\NormalTok{,])  }\OperatorTok{%>%}\StringTok{ }\KeywordTok{column_spec}\NormalTok{(}\DecValTok{15}\NormalTok{, }\DataTypeTok{bold =}\NormalTok{ F, }\DataTypeTok{border_left =}\NormalTok{ T) }\OperatorTok{%>%}\StringTok{ }\KeywordTok{scroll_box}\NormalTok{(}\DataTypeTok{width =} \StringTok{"100%"}\NormalTok{, }\DataTypeTok{box_css =} \StringTok{"border: 0px;"}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\begin{tabular}{l|l|l|l|l|l|l|l|l|l|l|l|l|l||>{}r|r|r}
\hline
  & AKT1 & CCNA1 & CTNNB1 & E2F1 & GRB2 & MAPK1 & MAPK14 & MAPK8 & MDM2 & PDK1 & SMAD7 & SRC & TSC1 & up & down & total\\
\hline
pert\_797158 & nochange & nochange & nochange & nochange & nochange & nochange & nochange & nochange & nochange & nochange & nochange & down & nochange & 0 & 1 & 1\\
\hline
pert\_265717 & down & nochange & nochange & nochange & nochange & nochange & nochange & nochange & nochange & nochange & nochange & down & nochange & 0 & 2 & 2\\
\hline
pert\_620011 & nochange & down & nochange & nochange & nochange & nochange & nochange & nochange & nochange & nochange & nochange & down & nochange & 0 & 2 & 2\\
\hline
pert\_738109 & nochange & nochange & down & nochange & nochange & nochange & nochange & nochange & nochange & nochange & nochange & down & nochange & 0 & 2 & 2\\
\hline
pert\_777475 & nochange & nochange & nochange & down & nochange & nochange & nochange & nochange & nochange & nochange & nochange & down & nochange & 0 & 2 & 2\\
\hline
pert\_790597 & nochange & nochange & nochange & nochange & down & nochange & nochange & nochange & nochange & nochange & nochange & down & nochange & 0 & 2 & 2\\
\hline
pert\_794971 & nochange & nochange & nochange & nochange & nochange & down & nochange & nochange & nochange & nochange & nochange & down & nochange & 0 & 2 & 2\\
\hline
pert\_796429 & nochange & nochange & nochange & nochange & nochange & nochange & down & nochange & nochange & nochange & nochange & down & nochange & 0 & 2 & 2\\
\hline
pert\_796915 & nochange & nochange & nochange & nochange & nochange & nochange & nochange & down & nochange & nochange & nochange & down & nochange & 0 & 2 & 2\\
\hline
pert\_797077 & nochange & nochange & nochange & nochange & nochange & nochange & nochange & nochange & down & nochange & nochange & down & nochange & 0 & 2 & 2\\
\hline
\end{tabular}

We can look to see if there are any trends in the orientation of the perturbations on FVS control nodes across the perturbations that passed both filtering criteria.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(data.table)}
\KeywordTok{library}\NormalTok{(ggplot2)}
\NormalTok{d3<-crit2_}\DecValTok{3}\NormalTok{[,}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{13}\NormalTok{)] }\OperatorTok{%>%}\StringTok{ }\KeywordTok{transpose}\NormalTok{() }\OperatorTok{%>%}\StringTok{ }\KeywordTok{as.matrix}\NormalTok{()}
\KeywordTok{row.names}\NormalTok{(d3)<-}\KeywordTok{colnames}\NormalTok{(crit2_}\DecValTok{3}\NormalTok{[}\DecValTok{1}\OperatorTok{:}\DecValTok{13}\NormalTok{])}
\KeywordTok{colnames}\NormalTok{(d3)<-}\KeywordTok{row.names}\NormalTok{(crit2_}\DecValTok{3}\NormalTok{)}
\NormalTok{d3r<-reshape2}\OperatorTok{::}\KeywordTok{melt}\NormalTok{(d3) }\OperatorTok{%>%}\StringTok{ }\KeywordTok{select}\NormalTok{(}\OperatorTok{-}\NormalTok{Var2)}

\CommentTok{#From Paul Tol: https://personal.sron.nl/~pault/}
\NormalTok{Tol_muted <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{'#88CCEE'}\NormalTok{, }\StringTok{'#44AA99'}\NormalTok{, }\StringTok{'#117733'}\NormalTok{, }\StringTok{'#332288'}\NormalTok{, }\StringTok{'#DDCC77'}\NormalTok{, }\StringTok{'#999933'}\NormalTok{,}\StringTok{'#CC6677'}\NormalTok{, }\StringTok{'#882255'}\NormalTok{, }\StringTok{'#AA4499'}\NormalTok{, }\StringTok{'#DDDDDD'}\NormalTok{)}

\KeywordTok{ggplot}\NormalTok{(d3r, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{value)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{Var1,}\DataTypeTok{scales =} \StringTok{"free_x"}\NormalTok{,}\DataTypeTok{shrink=}\OtherTok{FALSE}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ (..count..)}\OperatorTok{/}\KeywordTok{ncol}\NormalTok{(d3),}\DataTypeTok{fill=}\NormalTok{value))  }\OperatorTok{+}\StringTok{ }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{labels=}\NormalTok{scales}\OperatorTok{::}\NormalTok{percent) }\OperatorTok{+}\StringTok{ }\KeywordTok{scale_fill_manual}\NormalTok{(}\DataTypeTok{values=}\NormalTok{Tol_muted)}\OperatorTok{+}\StringTok{ }\KeywordTok{ylab}\NormalTok{(}\StringTok{"% of specified perturbation to an FVS control node across all }\CharTok{\textbackslash{}n}\StringTok{ combinations of perturbations that passed filtering criteria "}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{xlab}\NormalTok{(}\StringTok{"node perturbation"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}

{\centering \includegraphics{_main_files/figure-latex/unnamed-chunk-41-1} 

}

\caption{the precentage of specific perturbations on FVS control nodes in the perturbations that passed the filtering criteria}\label{fig:unnamed-chunk-41}
\end{figure}

Here, we see that in the majority of perturbations, SRC is knocked-out.

The steady-state values of the internal-marker nodes for these perturbations can be found in \href{https://github.com/VeraLiconaResearchGroup/Netisce/blob/main/colorectal_cancer_validation/results/3-marker-nodes/pert_internal_markers.txt}{\texttt{pert1\_internal\_markers.txt}}.

The combination BRAFi+SRCi treatment was identified and experimentally validated by Park et al., to overcome adaptive resistance to MAPK inhibitor therapy in HT29 cells. This perturbation, pert\_797158, passed both of our filtering criteria. We can plot the steady-state values of the internal-marker nodes for HT29\_BRAFi, H29\_BRAFi+EGFRi, and HT29\_BRAFi+SRCi using a radar plot.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(fmsb)}
\NormalTok{attr_pert<-}\KeywordTok{read.delim}\NormalTok{(}\StringTok{"crc/results/3-marker-nodes/pert_internal_markers.txt"}\NormalTok{,}\DataTypeTok{sep=}\StringTok{" "}\NormalTok{,}\DataTypeTok{row.names =} \DecValTok{1}\NormalTok{)}
\NormalTok{attr_pert <-attr_pert[}\KeywordTok{c}\NormalTok{(}\StringTok{'pert_797158'}\NormalTok{),]}
\NormalTok{exp<-}\KeywordTok{read.delim}\NormalTok{(}\StringTok{"crc/results/3-marker-nodes/exp_internalmarkers.txt"}\NormalTok{,}\DataTypeTok{sep=}\StringTok{" "}\NormalTok{,}\DataTypeTok{row.names =} \DecValTok{1}\NormalTok{)}
\NormalTok{exp<-exp[}\KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{),]}

\NormalTok{d1<-}\KeywordTok{rbind}\NormalTok{(exp,attr_pert)}
\KeywordTok{rownames}\NormalTok{(d1)[}\DecValTok{3}\NormalTok{]<-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"HT29_BRAFi+SRCi"}\NormalTok{)}
\NormalTok{maxcol<-}\KeywordTok{apply}\NormalTok{(d1, }\DecValTok{2}\NormalTok{, max)}
\NormalTok{mincol<-}\KeywordTok{apply}\NormalTok{(d1, }\DecValTok{2}\NormalTok{, min)}

\NormalTok{d2<-}\KeywordTok{rbind}\NormalTok{(maxcol,mincol, d1)}
\KeywordTok{rownames}\NormalTok{(d2)[}\DecValTok{1}\OperatorTok{:}\DecValTok{2}\NormalTok{]<-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Max"}\NormalTok{, }\StringTok{"Min"}\NormalTok{)}

\KeywordTok{par}\NormalTok{(}\DataTypeTok{mar =} \KeywordTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{, }\FloatTok{0.1}\NormalTok{, }\DecValTok{4}\NormalTok{, }\FloatTok{0.1}\NormalTok{))}


\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{5}\OperatorTok{:}\KeywordTok{nrow}\NormalTok{(d2)) \{}
  \KeywordTok{create_beautiful_radarchart}\NormalTok{(d2[}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{4}\NormalTok{, i), ],}\DataTypeTok{color =} \KeywordTok{c}\NormalTok{(}\StringTok{"#00AFBB"}\NormalTok{, }\StringTok{"#E7B800"}\NormalTok{,}\StringTok{"#FC4E07"}\NormalTok{),}\DataTypeTok{caxislabels =} \KeywordTok{seq}\NormalTok{(}\KeywordTok{round}\NormalTok{(}\KeywordTok{min}\NormalTok{(d2[}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{4}\NormalTok{, i),]),}\DecValTok{1}\NormalTok{),}\KeywordTok{round}\NormalTok{(}\KeywordTok{max}\NormalTok{(d2[}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{4}\NormalTok{, i),]),}\DecValTok{1}\NormalTok{),.}\DecValTok{2}\NormalTok{),}\DataTypeTok{title =}\KeywordTok{row.names}\NormalTok{(d2)[i]);}\KeywordTok{legend}\NormalTok{(}\DataTypeTok{x=}\FloatTok{0.4}\NormalTok{, }\DataTypeTok{y=}\FloatTok{1.4}\NormalTok{, }\DataTypeTok{legend =}\KeywordTok{c}\NormalTok{(}\KeywordTok{row.names}\NormalTok{(d2)[}\DecValTok{3}\OperatorTok{:}\KeywordTok{nrow}\NormalTok{(d2)]) , }\DataTypeTok{bty =} \StringTok{"n"}\NormalTok{, }\DataTypeTok{pch=}\DecValTok{20}\NormalTok{ , }\DataTypeTok{col=}\KeywordTok{c}\NormalTok{(}\StringTok{"#00AFBB"}\NormalTok{, }\StringTok{"#E7B800"}\NormalTok{,}\StringTok{"#FC4E07"}\NormalTok{) , }\DataTypeTok{text.col =} \StringTok{"black"}\NormalTok{, }\DataTypeTok{cex=}\DecValTok{1}\NormalTok{, }\DataTypeTok{pt.cex=}\DecValTok{2}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\textbackslash begin\{figure\}
\includegraphics[width=0.5\linewidth]{_main_files/figure-latex/crc-charts-1} \textbackslash caption\{radar charts of the steady-state values of 3 internal-marker nodes for HT29\_BRAFi+SRCi\}\label{fig:crc-charts}
\textbackslash end\{figure\}

We see here that the steady state value of CASP3 in the attractor produced from the HT29\_BRAFi+SRCi perturbation is within the range of attractor produced from the HT29\_BRAFi+EGFRi perturbation.

\hypertarget{results-using-apoptosis-proliferation-and-mapk-signaling-internal-marker-nodes}{%
\subsection{Results using apoptosis, proliferation, and MAPK signaling internal-marker nodes}\label{results-using-apoptosis-proliferation-and-mapk-signaling-internal-marker-nodes}}

We filtered the 52,703 perturbations using an additional 17 internal-marker nodes for the phenotypes of apoptosis, proliferation, and mapk signaling.

The individual results for all three sets can be found in their respective folders on github:
\href{https://github.com/VeraLiconaResearchGroup/Netisce/tree/main/colorectal_cancer_validation/results/apoptosis-marker-nodes}{\texttt{apoptosis-marker-nodes}}
\href{https://github.com/VeraLiconaResearchGroup/Netisce/tree/main/colorectal_cancer_validation/results/mapk-marker-nodes}{\texttt{mapk-marker-nodes}}
\href{https://github.com/VeraLiconaResearchGroup/Netisce/tree/main/colorectal_cancer_validation/results/proliferation-marker-nodes}{\texttt{proliferation-marker-nodes}}

We are interested in perturbations on FVS control nodes that pass the filtering criterion for each of the three phenotypes (i.e., the 90\% threshold for steady-state values is met separately for each of the sets of apoptosis, MAPK signaling, and proliferation nodes). We can plot the node perturbation trends for these perturbations.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{allthree<-crit2_}\DecValTok{3}\NormalTok{[}\KeywordTok{c}\NormalTok{(}\KeywordTok{Reduce}\NormalTok{(intersect, }\KeywordTok{list}\NormalTok{(}\KeywordTok{row.names}\NormalTok{(crit2_}\DecValTok{3}\NormalTok{),}\KeywordTok{row.names}\NormalTok{(crit2_apop),}\KeywordTok{row.names}\NormalTok{(crit2_prolif),}\KeywordTok{row.names}\NormalTok{(crit2_mapk)))),]}
\KeywordTok{print}\NormalTok{(}\KeywordTok{paste0}\NormalTok{(}\StringTok{'number of perturbations that pass filtering criteria 2: '}\NormalTok{,}\KeywordTok{nrow}\NormalTok{(allthree)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "number of perturbations that pass filtering criteria 2: 1266"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{d4<-allthree[,}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{13}\NormalTok{)] }\OperatorTok{%>%}\StringTok{ }\KeywordTok{transpose}\NormalTok{() }\OperatorTok{%>%}\StringTok{ }\KeywordTok{as.matrix}\NormalTok{()}
\KeywordTok{row.names}\NormalTok{(d4)<-}\KeywordTok{colnames}\NormalTok{(allthree[}\DecValTok{1}\OperatorTok{:}\DecValTok{13}\NormalTok{])}
\KeywordTok{colnames}\NormalTok{(d4)<-}\KeywordTok{row.names}\NormalTok{(allthree)}
\NormalTok{d4r<-reshape2}\OperatorTok{::}\KeywordTok{melt}\NormalTok{(d4) }\OperatorTok{%>%}\StringTok{ }\KeywordTok{select}\NormalTok{(}\OperatorTok{-}\NormalTok{Var2)}



\KeywordTok{ggplot}\NormalTok{(d4r, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{value)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{Var1,}\DataTypeTok{scales =} \StringTok{"free_x"}\NormalTok{,}\DataTypeTok{shrink=}\OtherTok{FALSE}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ (..count..)}\OperatorTok{/}\KeywordTok{ncol}\NormalTok{(d4),}\DataTypeTok{fill=}\NormalTok{value))  }\OperatorTok{+}\StringTok{ }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{labels=}\NormalTok{scales}\OperatorTok{::}\NormalTok{percent)}\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{panel.spacing.x =} \KeywordTok{unit}\NormalTok{(}\DecValTok{4}\NormalTok{, }\StringTok{"mm"}\NormalTok{)) }\OperatorTok{+}\StringTok{ }\KeywordTok{scale_fill_manual}\NormalTok{(}\DataTypeTok{values=}\NormalTok{Tol_muted) }\OperatorTok{+}\StringTok{ }\KeywordTok{ylab}\NormalTok{(}\StringTok{"% of specified perturbation to an FVS control node across all }\CharTok{\textbackslash{}n}\StringTok{ combinations of perturbations that passed filtering criteria "}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{xlab}\NormalTok{(}\StringTok{"node perturbation"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\includegraphics{_main_files/figure-latex/all-three-1.pdf}
\caption{\label{fig:all-three}the precentage of specific perturbations on FVS control nodes in the perturbations that passed the filtering criteria}
\end{figure}

For perturbations that pass the 2nd filtering criterion using internal-marker nodes for apoptosis, MAPK sigaling and proliferation, we see that in 100\% of the perturbations SRC is downregulated. In the majority of of perturbations, TSC1 is upregulated, and GRB2 is downregulated.

The two smallest sets of perturbations that passed the filtering criteria were BRAFi+SRCi+TSC1overexpression (pert\_797159) and BRAFi+SRCi+GRB2i (pert\_790597). We can make radar charts for each phenotype's internal marker nodes to show that the steady-state values for the internal marker-nodes produced from these perturbations are within the gene expression range of the MAPK inhibitor therapy sensitivty assocaited attractor (HT29\_BRAFi+EGFRi).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{attr_pert<-}\KeywordTok{read.delim}\NormalTok{(}\StringTok{"crc/results/apoptosis-marker-nodes/pert_internal_markers.txt"}\NormalTok{,}\DataTypeTok{sep=}\StringTok{" "}\NormalTok{,}\DataTypeTok{row.names =} \DecValTok{1}\NormalTok{)}
\NormalTok{attr_pert <-attr_pert[}\KeywordTok{c}\NormalTok{(}\StringTok{'pert_797159'}\NormalTok{,}\StringTok{'pert_790597'}\NormalTok{),]}
\NormalTok{exp<-}\KeywordTok{read.delim}\NormalTok{(}\StringTok{"crc/results/apoptosis-marker-nodes/exp_internalmarkers.txt"}\NormalTok{,}\DataTypeTok{sep=}\StringTok{" "}\NormalTok{,}\DataTypeTok{row.names =} \DecValTok{1}\NormalTok{)}
\NormalTok{exp<-exp[}\KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{),]}

\NormalTok{d1<-}\KeywordTok{rbind}\NormalTok{(exp,attr_pert)}
\KeywordTok{rownames}\NormalTok{(d1)[}\DecValTok{3}\OperatorTok{:}\DecValTok{4}\NormalTok{]<-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"HT29_BRAFi+SRCi+TSCovr"}\NormalTok{,}\StringTok{"HT29_BRAFi+SRCi+GRB2i"}\NormalTok{)}
\NormalTok{maxcol<-}\KeywordTok{apply}\NormalTok{(d1, }\DecValTok{2}\NormalTok{, max)}
\NormalTok{mincol<-}\KeywordTok{apply}\NormalTok{(d1, }\DecValTok{2}\NormalTok{, min)}

\NormalTok{d2<-}\KeywordTok{rbind}\NormalTok{(maxcol,mincol, d1)}
\KeywordTok{rownames}\NormalTok{(d2)[}\DecValTok{1}\OperatorTok{:}\DecValTok{2}\NormalTok{]<-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Max"}\NormalTok{, }\StringTok{"Min"}\NormalTok{)}

\KeywordTok{par}\NormalTok{(}\DataTypeTok{mar =} \KeywordTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{, }\FloatTok{0.1}\NormalTok{, }\DecValTok{4}\NormalTok{, }\FloatTok{0.1}\NormalTok{))}
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{5}\OperatorTok{:}\KeywordTok{nrow}\NormalTok{(d2)) \{}
  \KeywordTok{create_beautiful_radarchart}\NormalTok{(d2[}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{4}\NormalTok{, i), ],}\DataTypeTok{color =} \KeywordTok{c}\NormalTok{(}\StringTok{"#00AFBB"}\NormalTok{, }\StringTok{"#E7B800"}\NormalTok{,}\StringTok{"#FC4E07"}\NormalTok{),}\DataTypeTok{caxislabels =} \KeywordTok{seq}\NormalTok{(}\KeywordTok{round}\NormalTok{(}\KeywordTok{min}\NormalTok{(d2[}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{4}\NormalTok{, i),]),}\DecValTok{1}\NormalTok{),}\KeywordTok{round}\NormalTok{(}\KeywordTok{max}\NormalTok{(d2[}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{4}\NormalTok{, i),]),}\DecValTok{1}\NormalTok{),.}\DecValTok{2}\NormalTok{),}\DataTypeTok{title =}\KeywordTok{row.names}\NormalTok{(d2)[i]);}\KeywordTok{legend}\NormalTok{(}\DataTypeTok{x=}\FloatTok{0.4}\NormalTok{, }\DataTypeTok{y=}\FloatTok{1.4}\NormalTok{, }\DataTypeTok{legend =}\KeywordTok{c}\NormalTok{(}\KeywordTok{row.names}\NormalTok{(d2)[}\KeywordTok{c}\NormalTok{(}\DecValTok{3}\NormalTok{,}\DecValTok{4}\NormalTok{,i)]) , }\DataTypeTok{bty =} \StringTok{"n"}\NormalTok{, }\DataTypeTok{pch=}\DecValTok{20}\NormalTok{ , }\DataTypeTok{col=}\KeywordTok{c}\NormalTok{(}\StringTok{"#00AFBB"}\NormalTok{, }\StringTok{"#E7B800"}\NormalTok{,}\StringTok{"#FC4E07"}\NormalTok{) , }\DataTypeTok{text.col =} \StringTok{"black"}\NormalTok{, }\DataTypeTok{cex=}\DecValTok{1}\NormalTok{, }\DataTypeTok{pt.cex=}\DecValTok{2}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\textbackslash begin\{figure\}
\includegraphics[width=0.5\linewidth]{_main_files/figure-latex/crc-chartsapop-1} \includegraphics[width=0.5\linewidth]{_main_files/figure-latex/crc-chartsapop-2} \textbackslash caption\{radar charts of the steady-state values of apoptosis internal-marker nodes for HT29\_BRAFi+SRCi\_TSCovr and HT29\_BRAFi+SRCi\_GRB2i\}\label{fig:crc-chartsapop}
\textbackslash end\{figure\}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{attr_pert<-}\KeywordTok{read.delim}\NormalTok{(}\StringTok{"crc/results/proliferation-marker-nodes/pert_internal_markers.txt"}\NormalTok{,}\DataTypeTok{sep=}\StringTok{" "}\NormalTok{,}\DataTypeTok{row.names =} \DecValTok{1}\NormalTok{)}
\NormalTok{attr_pert <-attr_pert[}\KeywordTok{c}\NormalTok{(}\StringTok{'pert_797159'}\NormalTok{,}\StringTok{'pert_790597'}\NormalTok{),]}
\NormalTok{exp<-}\KeywordTok{read.delim}\NormalTok{(}\StringTok{"crc/results/proliferation-marker-nodes/exp_internalmarkers.txt"}\NormalTok{,}\DataTypeTok{sep=}\StringTok{" "}\NormalTok{,}\DataTypeTok{row.names =} \DecValTok{1}\NormalTok{)}
\NormalTok{exp<-exp[}\KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{),]}

\NormalTok{d1<-}\KeywordTok{rbind}\NormalTok{(exp,attr_pert)}
\KeywordTok{rownames}\NormalTok{(d1)[}\DecValTok{3}\OperatorTok{:}\DecValTok{4}\NormalTok{]<-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"HT29_BRAFi+SRCi+TSCovr"}\NormalTok{,}\StringTok{"HT29_BRAFi+SRCi+GRB2i"}\NormalTok{)}
\NormalTok{maxcol<-}\KeywordTok{apply}\NormalTok{(d1, }\DecValTok{2}\NormalTok{, max)}
\NormalTok{mincol<-}\KeywordTok{apply}\NormalTok{(d1, }\DecValTok{2}\NormalTok{, min)}

\NormalTok{d2<-}\KeywordTok{rbind}\NormalTok{(maxcol,mincol, d1)}
\KeywordTok{rownames}\NormalTok{(d2)[}\DecValTok{1}\OperatorTok{:}\DecValTok{2}\NormalTok{]<-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Max"}\NormalTok{, }\StringTok{"Min"}\NormalTok{)}

\KeywordTok{par}\NormalTok{(}\DataTypeTok{mar =} \KeywordTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{, }\FloatTok{0.1}\NormalTok{, }\DecValTok{4}\NormalTok{, }\FloatTok{0.1}\NormalTok{))}
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{5}\OperatorTok{:}\KeywordTok{nrow}\NormalTok{(d2)) \{}
  \KeywordTok{create_beautiful_radarchart}\NormalTok{(d2[}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{4}\NormalTok{, i), ],}\DataTypeTok{color =} \KeywordTok{c}\NormalTok{(}\StringTok{"#00AFBB"}\NormalTok{, }\StringTok{"#E7B800"}\NormalTok{,}\StringTok{"#FC4E07"}\NormalTok{),}\DataTypeTok{caxislabels =} \KeywordTok{seq}\NormalTok{(}\KeywordTok{round}\NormalTok{(}\KeywordTok{min}\NormalTok{(d2[}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{4}\NormalTok{, i),]),}\DecValTok{1}\NormalTok{),}\KeywordTok{round}\NormalTok{(}\KeywordTok{max}\NormalTok{(d2[}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{4}\NormalTok{, i),]),}\DecValTok{1}\NormalTok{),.}\DecValTok{2}\NormalTok{),}\DataTypeTok{title =}\KeywordTok{row.names}\NormalTok{(d2)[i]);}\CommentTok{#legend(x=0.4, y=1.4, legend =c(row.names(d2)[c(3,4,i)]) , bty = "n", pch=20 , col=c("#00AFBB", "#E7B800","#FC4E07") , text.col = "black", cex=1, pt.cex=2)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\textbackslash begin\{figure\}
\includegraphics[width=0.5\linewidth]{_main_files/figure-latex/crc-chartsprolif-1} \includegraphics[width=0.5\linewidth]{_main_files/figure-latex/crc-chartsprolif-2} \textbackslash caption\{radar charts of the steady-state values of apoptosis internal-marker nodes for HT29\_BRAFi+SRCi\_TSCovr and HT29\_BRAFi+SRCi\_GRB2i\}\label{fig:crc-chartsprolif}
\textbackslash end\{figure\}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{attr_pert<-}\KeywordTok{read.delim}\NormalTok{(}\StringTok{"crc/results/mapk-marker-nodes/pert_internal_markers.txt"}\NormalTok{,}\DataTypeTok{sep=}\StringTok{" "}\NormalTok{,}\DataTypeTok{row.names =} \DecValTok{1}\NormalTok{)}
\NormalTok{attr_pert <-attr_pert[}\KeywordTok{c}\NormalTok{(}\StringTok{'pert_797159'}\NormalTok{,}\StringTok{'pert_790597'}\NormalTok{),]}
\NormalTok{exp<-}\KeywordTok{read.delim}\NormalTok{(}\StringTok{"crc/results/mapk-marker-nodes/exp_internalmarkers.txt"}\NormalTok{,}\DataTypeTok{sep=}\StringTok{" "}\NormalTok{,}\DataTypeTok{row.names =} \DecValTok{1}\NormalTok{)}
\NormalTok{exp<-exp[}\KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{),]}

\NormalTok{d1<-}\KeywordTok{rbind}\NormalTok{(exp,attr_pert)}
\KeywordTok{rownames}\NormalTok{(d1)[}\DecValTok{3}\OperatorTok{:}\DecValTok{4}\NormalTok{]<-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"HT29_BRAFi+SRCi+TSCovr"}\NormalTok{,}\StringTok{"HT29_BRAFi+SRCi+GRB2i"}\NormalTok{)}
\NormalTok{maxcol<-}\KeywordTok{apply}\NormalTok{(d1, }\DecValTok{2}\NormalTok{, max)}
\NormalTok{mincol<-}\KeywordTok{apply}\NormalTok{(d1, }\DecValTok{2}\NormalTok{, min)}

\NormalTok{d2<-}\KeywordTok{rbind}\NormalTok{(maxcol,mincol, d1)}
\KeywordTok{rownames}\NormalTok{(d2)[}\DecValTok{1}\OperatorTok{:}\DecValTok{2}\NormalTok{]<-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Max"}\NormalTok{, }\StringTok{"Min"}\NormalTok{)}

\KeywordTok{par}\NormalTok{(}\DataTypeTok{mar =} \KeywordTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{, }\FloatTok{0.1}\NormalTok{, }\DecValTok{4}\NormalTok{, }\FloatTok{0.1}\NormalTok{))}
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{5}\OperatorTok{:}\KeywordTok{nrow}\NormalTok{(d2)) \{}
  \KeywordTok{create_beautiful_radarchart}\NormalTok{(d2[}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{4}\NormalTok{, i), ],}\DataTypeTok{color =} \KeywordTok{c}\NormalTok{(}\StringTok{"#00AFBB"}\NormalTok{, }\StringTok{"#E7B800"}\NormalTok{,}\StringTok{"#FC4E07"}\NormalTok{),}\DataTypeTok{caxislabels =} \KeywordTok{seq}\NormalTok{(}\KeywordTok{round}\NormalTok{(}\KeywordTok{min}\NormalTok{(d2[}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{4}\NormalTok{, i),]),}\DecValTok{1}\NormalTok{),}\KeywordTok{round}\NormalTok{(}\KeywordTok{max}\NormalTok{(d2[}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{4}\NormalTok{, i),]),}\DecValTok{1}\NormalTok{),.}\DecValTok{2}\NormalTok{),}\DataTypeTok{title =}\KeywordTok{row.names}\NormalTok{(d2)[i]);}\CommentTok{#legend(x=0.4, y=1.4, legend =c(row.names(d2)[c(3,4,i)]) , bty = "n", pch=20 , col=c("#00AFBB", "#E7B800","#FC4E07") , text.col = "black", cex=1, pt.cex=2)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\textbackslash begin\{figure\}
\includegraphics[width=0.5\linewidth]{_main_files/figure-latex/crc-chartsmapk-1} \includegraphics[width=0.5\linewidth]{_main_files/figure-latex/crc-chartsmapk-2} \textbackslash caption\{radar charts of the steady-state values of apoptosis internal-marker nodes for HT29\_BRAFi+SRCi\_TSCovr and HT29\_BRAFi+SRCi\_GRB2i\}\label{fig:crc-chartsmapk}
\textbackslash end\{figure\}

\hypertarget{netisce-in-galaxy-project}{%
\chapter{NETISCE in Galaxy Project}\label{netisce-in-galaxy-project}}

We have implemented NETISCE as a Galaxy Project tool. This allows users to run NETISCE analysis without programming knowledge. Herein are brief instructions for downloading and installing the Galaxy Project Tool and Workflow.

\hypertarget{installing-galaxy}{%
\section{Installing Galaxy}\label{installing-galaxy}}

Please follow the instructions for installing a local version of Galaxy here: \url{https://galaxyproject.org/admin/get-galaxy/}

Follow instructions up to ``Install Tools''.

\hypertarget{installing-the-netisce-tool-from-galaxy-tool-shed.}{%
\section{Installing the NETISCE tool from Galaxy Tool Shed.}\label{installing-the-netisce-tool-from-galaxy-tool-shed.}}

First launch Galaxy by inputting \texttt{sh\ run.sh} in your terminal and load the GUI (navigate to \texttt{http://localhost:8080/} in your browser of choice). Then, after you have established your admin account and are logged in, you will be able to download the NETSICE tool.

Click on the Admin button in the top ribbon:

\begin{center}\includegraphics[width=1\linewidth]{images/galaxy1} \end{center}

Under Tool Management, select ``Install and Uninstall''. This will lead you to the search repositories page. You can search for the NETISCE tool by typing ``netisce'' into the search bar.

Click on ``netisce'' and select Install. You can choose to Install additional dependencies (this is especially useful if you have installed Galaxy in a conda environment). You can specify the header under which you want to install netisce (we suggest ``NETISCE'')

\begin{center}\includegraphics[width=1\linewidth]{images/galaxy2} \end{center}

\hypertarget{downloading-the-netisce-workflow.}{%
\section{Downloading the NETISCE workflow.}\label{downloading-the-netisce-workflow.}}

The fastest way to download the NETISCE workflow is to direct download it from here: \url{https://github.com/VeraLiconaResearchGroup/Netisce/blob/049aec40e76c6b1d965aa199a041e0651fadd29b/Galaxy-Workflow-NETISCE.ga}

Alternatively, you can launch galaxy from \url{https://usegalaxy.org/}

In the upper ribbon, navigate to ``Shared Data'' -\textgreater{} ``Workflows''. Here you can search for ``netisce''

\begin{center}\includegraphics[width=1\linewidth]{images/galaxy3} \end{center}

Click the dropdown arrow and select ``save as file.''

\begin{center}\includegraphics[width=1\linewidth]{images/galaxy4} \end{center}

Using either downloaded file, in your local Galaxy, navigate to the ``Workflow'' page. Select import in the right-hand corner. Upload the .ga file.

Once the Netisce workflow appears, on the righthand side, press the run button

\begin{center}\includegraphics[width=1\linewidth]{images/galaxy5} \end{center}

This will load the workflow.You will be presented with parameters to fill in (either text or files). You can use the same sample files as are used in the toy example nextflow run. Once you have uploaded your files and filled in other parameters, press ``Run Workflow''.

\begin{center}\includegraphics[width=1\linewidth]{images/galaxy6} \end{center}

You can monitor the progress of your run on the right hand side. when all jobs are complete, you can view the report of your workflow, which contains all resutls files.

\begin{center}\includegraphics[width=1\linewidth]{images/galaxy7} \end{center}

  \bibliography{book.bib,packages.bib}

\end{document}
